import {
  SkinOutlined,
  TeamOutlined,
  ToolOutlined,
  ShopOutlined,
  UserOutlined,
  DatabaseOutlined,
  InboxOutlined,
  DropboxOutlined,
} from '@ant-design/icons';
import type { TabConfig } from './types';

export const TAB_CONFIGS: TabConfig[] = [
  {
    key: 'style',
    label: '款式资料',
    icon: <SkinOutlined />,
    description: '导入款式基础信息，包括款号、款名、品类、颜色、码数等',
    requiredFields: '款号（必填）',
    tips: [
      '款号必须唯一，重复的款号会导入失败',
      '颜色和码数支持多个，用逗号分隔（如：红色,白色）',
      '单次最多导入 500 条',
    ],
  },
  {
    key: 'factory',
    label: '供应商',
    icon: <ShopOutlined />,
    description: '导入合作供应商/工厂信息',
    requiredFields: '供应商名称（必填）',
    tips: [
      '供应商名称必须唯一',
      '导入后默认为"启用"状态',
      '单次最多导入 500 条',
    ],
  },
  {
    key: 'customer',
    label: '客户',
    icon: <UserOutlined />,
    description: '导入客户（品牌方/贸易公司）档案，下单与 CRM 共用',
    requiredFields: '客户名称（必填）',
    failedColumns: [{ title: '客户名称', dataIndex: 'companyName', width: 180 }],
    tips: [
      '客户名称必须唯一',
      '客户编号由系统自动生成，等级不填默认 3 级',
      '单次最多导入 500 条',
    ],
  },
  {
    key: 'material',
    label: '物料主档',
    icon: <DatabaseOutlined />,
    description: '导入物料资料主档（编码、类型、成分、供应商等）',
    requiredFields: '物料编码 + 物料名称（必填）',
    failedColumns: [{ title: '物料编码', dataIndex: 'materialCode', width: 130 }],
    tips: [
      '物料编码必须唯一——后续「物料期初库存」导入靠它对应物料',
      '供应商名称必须是系统中已存在的供应商（先导入供应商）',
      '导入后即为「完善」状态，BOM / 采购立即可选',
      '单次最多导入 500 条',
    ],
  },
  {
    key: 'material-stock',
    label: '物料期初库存',
    icon: <InboxOutlined />,
    description: '把现有面料/辅料库存搬进系统，每行落一条入库台账（可审计）',
    requiredFields: '物料编码 + 数量（必填）',
    failedColumns: [{ title: '物料编码', dataIndex: 'materialCode', width: 130 }],
    tips: [
      '物料编码必须是「物料主档」中已存在的（推荐顺序：物料主档 → 期初库存）',
      '数量支持小数（面料按米/公斤），为累加语义，与页面「手动入库」一致',
      '同一物料不同颜色/规格/仓位拆多行填',
      '单次最多导入 500 条',
    ],
  },
  {
    key: 'product-stock',
    label: '成品期初库存',
    icon: <DropboxOutlined />,
    description: '把现有成品库存搬进系统（按款号+颜色+码数），每行落一条入库台账',
    requiredFields: '款号 + 数量（必填）',
    failedColumns: [{ title: '款号', dataIndex: 'styleNo', width: 130 }],
    tips: [
      '款号必须是系统中已导入的款式（推荐顺序：款式 → 成品期初库存）',
      '数量为正整数，累加语义，与成品仓储页「自由入库」一致',
      '同一款号多颜色多码数拆多行填',
      '单次最多导入 500 条',
    ],
  },
  {
    key: 'employee',
    label: '员工',
    icon: <TeamOutlined />,
    description: '导入员工/工人信息，系统自动创建账号',
    requiredFields: '姓名（必填）',
    tips: [
      '系统会自动生成用户名',
      '默认密码为 123456，请通知员工修改',
      '角色默认为"普通用户"',
      '单次最多导入 500 条',
    ],
  },
  {
    key: 'process',
    label: '工序',
    icon: <ToolOutlined />,
    description: '为已有款式导入工序模板（裁剪、车缝等）',
    requiredFields: '款号 + 工序名称（必填）',
    tips: [
      '款号必须是系统中已存在的，请先导入款式',
      '同一款号下可以有多道工序',
      '工序编码为空时会自动生成 P1, P2...',
      '进度节点可选：采购/裁剪/车缝/尾部/入库',
    ],
  },
];
