DROP PROCEDURE IF EXISTS AddStyleInfoColumns;

DELIMITER //

CREATE PROCEDURE AddStyleInfoColumns()
BEGIN
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 't_style_info' AND COLUMN_NAME = 'fabric_composition') THEN
        ALTER TABLE t_style_info ADD COLUMN fabric_composition VARCHAR(500);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 't_style_info' AND COLUMN_NAME = 'wash_instructions') THEN
        ALTER TABLE t_style_info ADD COLUMN wash_instructions VARCHAR(500);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 't_style_info' AND COLUMN_NAME = 'u_code') THEN
        ALTER TABLE t_style_info ADD COLUMN u_code VARCHAR(100);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 't_style_info' AND COLUMN_NAME = 'fabric_composition_parts') THEN
        ALTER TABLE t_style_info ADD COLUMN fabric_composition_parts TEXT;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 't_style_info' AND COLUMN_NAME = 'wash_temp_code') THEN
        ALTER TABLE t_style_info ADD COLUMN wash_temp_code VARCHAR(20);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 't_style_info' AND COLUMN_NAME = 'bleach_code') THEN
        ALTER TABLE t_style_info ADD COLUMN bleach_code VARCHAR(20);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 't_style_info' AND COLUMN_NAME = 'tumble_dry_code') THEN
        ALTER TABLE t_style_info ADD COLUMN tumble_dry_code VARCHAR(20);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 't_style_info' AND COLUMN_NAME = 'iron_code') THEN
        ALTER TABLE t_style_info ADD COLUMN iron_code VARCHAR(20);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 't_style_info' AND COLUMN_NAME = 'dry_clean_code') THEN
        ALTER TABLE t_style_info ADD COLUMN dry_clean_code VARCHAR(20);
    END IF;

    SELECT 'Done' as result;
END//

DELIMITER ;

CALL AddStyleInfoColumns;

DROP PROCEDURE IF EXISTS AddStyleInfoColumns;

SELECT COUNT(*) as final_columns FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'fashion_supplychain' AND TABLE_NAME = 't_style_info';