package com.fashion.supplychain.config;

import java.util.LinkedHashMap;

public final class DbTableDefinitions {

    static final LinkedHashMap<String, String> TABLE_FIXES = new LinkedHashMap<>();

    static {
        addMissingTables();
    }

    private DbTableDefinitions() {}
    public static void addMissingTables() {
        TABLE_FIXES.put("t_intelligence_audit_log",
            "CREATE TABLE IF NOT EXISTS `t_intelligence_audit_log` ("
            + "`id` VARCHAR(32) NOT NULL COMMENT '审计日志ID',"
            + "`tenant_id` BIGINT NOT NULL DEFAULT 0 COMMENT '租户ID',"
            + "`command_id` VARCHAR(64) DEFAULT NULL COMMENT '命令ID',"
            + "`action` VARCHAR(100) DEFAULT NULL COMMENT '命令类型',"
            + "`target_id` VARCHAR(100) DEFAULT NULL COMMENT '目标对象ID',"
            + "`executor_id` VARCHAR(64) DEFAULT NULL COMMENT '执行人ID',"
            + "`status` VARCHAR(32) DEFAULT 'EXECUTING' COMMENT '执行状态',"
            + "`reason` VARCHAR(500) DEFAULT NULL COMMENT '命令原始理由',"
            + "`risk_level` INT DEFAULT NULL COMMENT '风险等级',"
            + "`result_data` TEXT DEFAULT NULL COMMENT '执行结果JSON',"
            + "`error_message` TEXT DEFAULT NULL COMMENT '错误信息',"
            + "`duration_ms` BIGINT DEFAULT NULL COMMENT '执行耗时',"
            + "`remark` VARCHAR(500) DEFAULT NULL COMMENT '备注',"
            + "`created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',"
            + "`requires_approval` TINYINT(1) DEFAULT 0 COMMENT '是否需要人工审批',"
            + "`approved_by` VARCHAR(64) DEFAULT NULL COMMENT '审批人ID',"
            + "`approved_at` DATETIME DEFAULT NULL COMMENT '审批时间',"
            + "`approval_remark` VARCHAR(500) DEFAULT NULL COMMENT '审批备注',"
            + "PRIMARY KEY (`id`),"
            + "KEY `idx_audit_tenant_status` (`tenant_id`, `status`),"
            + "KEY `idx_audit_command_id` (`command_id`),"
            + "KEY `idx_audit_created_at` (`tenant_id`, `created_at`)"
            + ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='智能执行审计日志'");
        TABLE_FIXES.put("t_agent_meeting",
            "CREATE TABLE IF NOT EXISTS `t_agent_meeting` ("
            + "`id` BIGINT NOT NULL AUTO_INCREMENT,"
            + "`tenant_id` BIGINT NOT NULL,"
            + "`meeting_type` VARCHAR(50) NOT NULL,"
            + "`topic` VARCHAR(300) NOT NULL,"
            + "`participants` VARCHAR(500) DEFAULT NULL,"
            + "`agenda` TEXT DEFAULT NULL,"
            + "`debate_rounds` TEXT DEFAULT NULL,"
            + "`consensus` TEXT DEFAULT NULL,"
            + "`dissent` TEXT DEFAULT NULL,"
            + "`action_items` TEXT DEFAULT NULL,"
            + "`confidence_score` INT DEFAULT NULL,"
            + "`linked_decision_ids` VARCHAR(500) DEFAULT NULL,"
            + "`linked_rca_ids` VARCHAR(500) DEFAULT NULL,"
            + "`duration_ms` BIGINT DEFAULT NULL,"
            + "`status` VARCHAR(20) DEFAULT 'concluded',"
            + "`delete_flag` INT DEFAULT 0,"
            + "`create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,"
            + "PRIMARY KEY (`id`),"
            + "KEY `idx_am_tenant_type` (`tenant_id`, `meeting_type`),"
            + "KEY `idx_am_create_time` (`create_time`)"
            + ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='Agent例会'");
        TABLE_FIXES.put("t_material_pickup_record",
            "CREATE TABLE IF NOT EXISTS `t_material_pickup_record` ("
            + "`id` VARCHAR(64) NOT NULL COMMENT '主键UUID',"
            + "`tenant_id` BIGINT DEFAULT NULL COMMENT '租户ID',"
            + "`pickup_no` VARCHAR(64) NOT NULL COMMENT '领取单号',"
            + "`pickup_type` VARCHAR(20) NOT NULL DEFAULT 'INTERNAL' COMMENT '领取类型',"
            + "`order_no` VARCHAR(100) DEFAULT NULL COMMENT '关联生产订单号',"
            + "`style_no` VARCHAR(100) DEFAULT NULL COMMENT '关联款号',"
            + "`material_id` VARCHAR(64) DEFAULT NULL COMMENT '物料ID',"
            + "`material_code` VARCHAR(100) DEFAULT NULL COMMENT '物料编号',"
            + "`material_name` VARCHAR(200) DEFAULT NULL COMMENT '物料名称',"
            + "`material_type` VARCHAR(50) DEFAULT NULL COMMENT '物料类型',"
            + "`color` VARCHAR(100) DEFAULT NULL COMMENT '颜色',"
            + "`specification` VARCHAR(200) DEFAULT NULL COMMENT '规格',"
            + "`quantity` DECIMAL(14,3) DEFAULT NULL COMMENT '领取数量',"
            + "`unit` VARCHAR(20) DEFAULT NULL COMMENT '单位',"
            + "`unit_price` DECIMAL(14,4) DEFAULT NULL COMMENT '单价',"
            + "`amount` DECIMAL(14,2) DEFAULT NULL COMMENT '金额小计',"
            + "`picker_id` VARCHAR(64) DEFAULT NULL COMMENT '领取人ID',"
            + "`picker_name` VARCHAR(100) DEFAULT NULL COMMENT '领取人姓名',"
            + "`pickup_time` DATETIME DEFAULT NULL COMMENT '领取时间',"
            + "`audit_status` VARCHAR(20) NOT NULL DEFAULT 'PENDING' COMMENT '审核状态',"
            + "`auditor_id` VARCHAR(64) DEFAULT NULL COMMENT '审核人ID',"
            + "`auditor_name` VARCHAR(100) DEFAULT NULL COMMENT '审核人姓名',"
            + "`audit_time` DATETIME DEFAULT NULL COMMENT '审核时间',"
            + "`audit_remark` VARCHAR(500) DEFAULT NULL COMMENT '审核备注',"
            + "`finance_status` VARCHAR(20) NOT NULL DEFAULT 'PENDING' COMMENT '财务状态',"
            + "`finance_remark` VARCHAR(500) DEFAULT NULL COMMENT '财务核算备注',"
            + "`remark` VARCHAR(500) DEFAULT NULL COMMENT '领取备注',"
            + "`create_time` DATETIME DEFAULT NULL COMMENT '创建时间',"
            + "`update_time` DATETIME DEFAULT NULL COMMENT '更新时间',"
            + "`delete_flag` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '删除标记',"
            + "PRIMARY KEY (`id`),"
            + "KEY `idx_mpick_tenant_audit` (`tenant_id`, `audit_status`),"
            + "KEY `idx_mpick_order_style` (`order_no`, `style_no`),"
            + "KEY `idx_mpick_finance` (`tenant_id`, `finance_status`),"
            + "KEY `idx_mpick_create_time` (`create_time`)"
            + ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='面辅料领取记录'");
        TABLE_FIXES.put("t_hyper_advisor_session",
            "CREATE TABLE IF NOT EXISTS `t_hyper_advisor_session` ("
            + "`id` BIGINT NOT NULL AUTO_INCREMENT,"
            + "`tenant_id` BIGINT NOT NULL,"
            + "`user_id` VARCHAR(64) NOT NULL,"
            + "`session_id` VARCHAR(128) NOT NULL,"
            + "`role` VARCHAR(32) DEFAULT NULL,"
            + "`content` LONGTEXT DEFAULT NULL,"
            + "`metadata_json` TEXT DEFAULT NULL,"
            + "`create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,"
            + "`delete_flag` INT NOT NULL DEFAULT 0,"
            + "PRIMARY KEY (`id`),"
            + "KEY `idx_session_id` (`session_id`),"
            + "KEY `idx_tenant_user` (`tenant_id`, `user_id`),"
            + "KEY `idx_tenant_create` (`tenant_id`, `create_time`)"
            + ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='超级顾问会话记录'");
        TABLE_FIXES.put("t_advisor_feedback",
            "CREATE TABLE IF NOT EXISTS `t_advisor_feedback` ("
            + "`id` BIGINT NOT NULL AUTO_INCREMENT,"
            + "`tenant_id` BIGINT NOT NULL,"
            + "`user_id` VARCHAR(64) NOT NULL,"
            + "`session_id` VARCHAR(64) NOT NULL,"
            + "`trace_id` VARCHAR(64) DEFAULT NULL,"
            + "`query_text` TEXT NOT NULL,"
            + "`advice_text` TEXT NOT NULL,"
            + "`score` DOUBLE NOT NULL DEFAULT 0,"
            + "`feedback_text` VARCHAR(500) DEFAULT NULL,"
            + "`harvested` TINYINT NOT NULL DEFAULT 0,"
            + "`harvested_kb_id` VARCHAR(64) DEFAULT NULL,"
            + "`create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,"
            + "PRIMARY KEY (`id`),"
            + "KEY `idx_feedback_harvest` (`harvested`, `score`)"
            + ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='超级顾问反馈'");
        TABLE_FIXES.put("t_ai_user_profile",
            "CREATE TABLE IF NOT EXISTS `t_ai_user_profile` ("
            + "`id` BIGINT NOT NULL AUTO_INCREMENT,"
            + "`tenant_id` BIGINT NOT NULL,"
            + "`user_id` VARCHAR(64) NOT NULL,"
            + "`behavior_summary` TEXT DEFAULT NULL,"
            + "`preferences_json` LONGTEXT DEFAULT NULL,"
            + "`create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,"
            + "`update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,"
            + "PRIMARY KEY (`id`),"
            + "UNIQUE KEY `uk_tenant_user` (`tenant_id`, `user_id`),"
            + "KEY `idx_tenant_id` (`tenant_id`)"
            + ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI用户画像'");
        TABLE_FIXES.put("t_purchase_order_doc",
            "CREATE TABLE IF NOT EXISTS `t_purchase_order_doc` ("
            + "`id` VARCHAR(36) NOT NULL,"
            + "`tenant_id` BIGINT NOT NULL,"
            + "`order_no` VARCHAR(100) NOT NULL,"
            + "`image_url` VARCHAR(1000) NOT NULL,"
            + "`raw_text` TEXT DEFAULT NULL,"
            + "`match_count` INT NOT NULL DEFAULT 0,"
            + "`total_recognized` INT NOT NULL DEFAULT 0,"
            + "`uploader_id` VARCHAR(36) DEFAULT NULL,"
            + "`uploader_name` VARCHAR(100) DEFAULT NULL,"
            + "`create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,"
            + "`delete_flag` INT NOT NULL DEFAULT 0,"
            + "PRIMARY KEY (`id`),"
            + "KEY `idx_pod_order_no` (`order_no`),"
            + "KEY `idx_pod_tenant_id` (`tenant_id`)"
            + ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='采购单据上传记录表'");
        TABLE_FIXES.put("t_material_database",
            "CREATE TABLE IF NOT EXISTS `t_material_database` ("
            + "`id` VARCHAR(36) NOT NULL,"
            + "`material_code` VARCHAR(50) NOT NULL,"
            + "`material_name` VARCHAR(100) NOT NULL,"
            + "`style_no` VARCHAR(50) DEFAULT NULL,"
            + "`material_type` VARCHAR(20) DEFAULT 'accessory',"
            + "`color` VARCHAR(50) DEFAULT NULL,"
            + "`fabric_width` VARCHAR(50) DEFAULT NULL,"
            + "`fabric_weight` VARCHAR(50) DEFAULT NULL,"
            + "`fabric_composition` VARCHAR(100) DEFAULT NULL,"
            + "`specifications` VARCHAR(100) DEFAULT NULL,"
            + "`unit` VARCHAR(20) NOT NULL DEFAULT '',"
            + "`supplier_id` VARCHAR(36) DEFAULT NULL,"
            + "`supplier_name` VARCHAR(100) DEFAULT NULL,"
            + "`supplier_contact_person` VARCHAR(100) DEFAULT NULL,"
            + "`supplier_contact_phone` VARCHAR(50) DEFAULT NULL,"
            + "`unit_price` DECIMAL(10,2) DEFAULT 0.00,"
            + "`description` VARCHAR(255) DEFAULT NULL,"
            + "`image` VARCHAR(500) DEFAULT NULL,"
            + "`remark` VARCHAR(500) DEFAULT NULL,"
            + "`status` VARCHAR(20) DEFAULT 'pending',"
            + "`completed_time` DATETIME DEFAULT NULL,"
            + "`return_reason` VARCHAR(255) DEFAULT NULL,"
            + "`tenant_id` BIGINT DEFAULT NULL,"
            + "`create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,"
            + "`update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,"
            + "`delete_flag` INT NOT NULL DEFAULT 0,"
            + "PRIMARY KEY (`id`),"
            + "KEY `idx_material_code` (`material_code`),"
            + "KEY `idx_style_no` (`style_no`),"
            + "KEY `idx_supplier_name` (`supplier_name`)"
            + ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='面辅料数据库'");
        TABLE_FIXES.put("t_intelligence_metrics",
            "CREATE TABLE IF NOT EXISTS `t_intelligence_metrics` ("
            + "`id` BIGINT NOT NULL AUTO_INCREMENT,"
            + "`tenant_id` BIGINT NOT NULL,"
            + "`scene` VARCHAR(100) NOT NULL,"
            + "`provider` VARCHAR(50) DEFAULT NULL,"
            + "`model` VARCHAR(100) DEFAULT NULL,"
            + "`trace_id` VARCHAR(64) DEFAULT NULL,"
            + "`trace_url` VARCHAR(500) DEFAULT NULL,"
            + "`success` TINYINT(1) NOT NULL DEFAULT 0,"
            + "`fallback_used` TINYINT(1) NOT NULL DEFAULT 0,"
            + "`latency_ms` INT DEFAULT NULL,"
            + "`prompt_chars` INT DEFAULT NULL,"
            + "`response_chars` INT DEFAULT NULL,"
            + "`tool_call_count` INT DEFAULT NULL,"
            + "`error_message` VARCHAR(500) DEFAULT NULL,"
            + "`user_id` VARCHAR(64) DEFAULT NULL,"
            + "`create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,"
            + "`delete_flag` TINYINT(1) NOT NULL DEFAULT 0,"
            + "PRIMARY KEY (`id`),"
            + "KEY `idx_metrics_tenant_scene` (`tenant_id`, `scene`, `create_time`),"
            + "KEY `idx_metrics_create_time` (`create_time`)"
            + ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='智能模块AI调用度量表'");
        TABLE_FIXES.put("t_intelligence_signal",
            "CREATE TABLE IF NOT EXISTS `t_intelligence_signal` ("
            + "`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,"
            + "`tenant_id` BIGINT NOT NULL,"
            + "`signal_type` VARCHAR(50) NOT NULL,"
            + "`signal_code` VARCHAR(100) NOT NULL,"
            + "`signal_level` VARCHAR(20) NOT NULL DEFAULT 'info',"
            + "`source_domain` VARCHAR(50) DEFAULT NULL,"
            + "`source_id` VARCHAR(100) DEFAULT NULL,"
            + "`source_name` VARCHAR(200) DEFAULT NULL,"
            + "`signal_title` VARCHAR(500) DEFAULT NULL,"
            + "`signal_detail` TEXT DEFAULT NULL,"
            + "`signal_analysis` TEXT DEFAULT NULL,"
            + "`related_ids` VARCHAR(500) DEFAULT NULL,"
            + "`priority_score` INT NOT NULL DEFAULT 50,"
            + "`status` VARCHAR(20) NOT NULL DEFAULT 'open',"
            + "`resolved_at` DATETIME DEFAULT NULL,"
            + "`create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,"
            + "`update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,"
            + "`delete_flag` INT NOT NULL DEFAULT 0,"
            + "PRIMARY KEY (`id`),"
            + "KEY `idx_tenant_status` (`tenant_id`, `status`, `create_time`),"
            + "KEY `idx_tenant_level` (`tenant_id`, `signal_level`, `priority_score`)"
            + ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='统一智能信号表'");
        TABLE_FIXES.put("t_intelligence_action_task_feedback",
            "CREATE TABLE IF NOT EXISTS `t_intelligence_action_task_feedback` ("
            + "`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,"
            + "`tenant_id` BIGINT NOT NULL,"
            + "`task_code` VARCHAR(100) NOT NULL,"
            + "`related_order_no` VARCHAR(64) DEFAULT NULL,"
            + "`feedback_status` VARCHAR(32) NOT NULL,"
            + "`feedback_reason` VARCHAR(500) DEFAULT NULL,"
            + "`completion_note` VARCHAR(500) DEFAULT NULL,"
            + "`source_signal` VARCHAR(100) DEFAULT NULL,"
            + "`next_review_at` VARCHAR(32) DEFAULT NULL,"
            + "`operator_id` VARCHAR(64) DEFAULT NULL,"
            + "`operator_name` VARCHAR(100) DEFAULT NULL,"
            + "`create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,"
            + "`update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,"
            + "`delete_flag` INT NOT NULL DEFAULT 0,"
            + "PRIMARY KEY (`id`),"
            + "KEY `idx_tenant_task` (`tenant_id`, `task_code`, `related_order_no`, `create_time`),"
            + "KEY `idx_tenant_status` (`tenant_id`, `feedback_status`, `create_time`)"
            + ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='动作中心任务回执表'");
        TABLE_FIXES.put("t_order_remark",
            "CREATE TABLE IF NOT EXISTS `t_order_remark` ("
            + "`id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',"
            + "`target_type` VARCHAR(20) NOT NULL COMMENT 'order=大货订单 style=样衣开发',"
            + "`target_no` VARCHAR(100) NOT NULL COMMENT '订单号或款号',"
            + "`author_id` VARCHAR(64) DEFAULT NULL COMMENT '填写人ID',"
            + "`author_name` VARCHAR(100) DEFAULT NULL COMMENT '填写人姓名',"
            + "`author_role` VARCHAR(100) DEFAULT NULL COMMENT '填写人角色',"
            + "`content` TEXT NOT NULL COMMENT '备注内容',"
            + "`tenant_id` BIGINT NOT NULL COMMENT '租户ID',"
            + "`create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',"
            + "`delete_flag` INT NOT NULL DEFAULT 0 COMMENT '删除标记',"
            + "PRIMARY KEY (`id`),"
            + "KEY `idx_remark_target` (`tenant_id`,`target_type`,`target_no`),"
            + "KEY `idx_remark_time` (`tenant_id`,`create_time`)"
            + ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='订单/款式备注'");
        TABLE_FIXES.put("t_agent_execution_log",
            "CREATE TABLE IF NOT EXISTS `t_agent_execution_log` ("
            + "`id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',"
            + "`tenant_id` BIGINT NOT NULL COMMENT '租户ID',"
            + "`scene` VARCHAR(50) DEFAULT NULL COMMENT '分析场景',"
            + "`route` VARCHAR(100) DEFAULT NULL COMMENT 'Supervisor路由决策',"
            + "`context_summary` TEXT DEFAULT NULL COMMENT '分析摘要文本',"
            + "`reflection` TEXT DEFAULT NULL COMMENT 'LLM批判性反思内容',"
            + "`optimization_suggestion` TEXT DEFAULT NULL COMMENT '优化建议',"
            + "`confidence_score` INT DEFAULT 0 COMMENT '置信分0-100',"
            + "`status` VARCHAR(20) DEFAULT 'COMPLETED' COMMENT 'COMPLETED|ERROR',"
            + "`latency_ms` BIGINT DEFAULT 0 COMMENT '执行耗时(毫秒)',"
            + "`create_time` DATETIME DEFAULT NULL COMMENT '执行时间',"
            + "PRIMARY KEY (`id`),"
            + "KEY `idx_aex_tenant_time` (`tenant_id`,`create_time`)"
            + ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='多代理图执行日志'");
        TABLE_FIXES.put("t_product_outstock",
            "CREATE TABLE IF NOT EXISTS `t_product_outstock` ("
            + "`id` VARCHAR(64) NOT NULL, "
            + "`outstock_no` VARCHAR(64) DEFAULT NULL, "
            + "`order_id` VARCHAR(64) DEFAULT NULL, "
            + "`order_no` VARCHAR(64) DEFAULT NULL, "
            + "`style_id` VARCHAR(64) DEFAULT NULL, "
            + "`style_no` VARCHAR(64) DEFAULT NULL, "
            + "`style_name` VARCHAR(200) DEFAULT NULL, "
            + "`outstock_quantity` INT DEFAULT 0, "
            + "`outstock_type` VARCHAR(32) DEFAULT NULL, "
            + "`warehouse` VARCHAR(100) DEFAULT NULL, "
            + "`remark` TEXT, "
            + "`create_time` DATETIME DEFAULT NULL, "
            + "`update_time` DATETIME DEFAULT NULL, "
            + "`delete_flag` INT DEFAULT 0, "
            + "`operator_id` VARCHAR(64) DEFAULT NULL, "
            + "`operator_name` VARCHAR(100) DEFAULT NULL, "
            + "`creator_id` VARCHAR(64) DEFAULT NULL, "
            + "`creator_name` VARCHAR(100) DEFAULT NULL, "
            + "`tenant_id` BIGINT DEFAULT NULL, "
            + "`sku_code` VARCHAR(100) DEFAULT NULL, "
            + "`color` VARCHAR(50) DEFAULT NULL, "
            + "`size` VARCHAR(50) DEFAULT NULL, "
            + "`cost_price` DECIMAL(12,2) DEFAULT NULL, "
            + "`sales_price` DECIMAL(12,2) DEFAULT NULL, "
            + "`tracking_no` VARCHAR(100) DEFAULT NULL, "
            + "`express_company` VARCHAR(50) DEFAULT NULL, "
            + "`receive_status` VARCHAR(20) DEFAULT NULL, "
            + "`receive_time` DATETIME DEFAULT NULL, "
            + "`received_by` VARCHAR(36) DEFAULT NULL, "
            + "`received_by_name` VARCHAR(100) DEFAULT NULL, "
            + "`customer_name` VARCHAR(100) DEFAULT NULL, "
            + "`customer_phone` VARCHAR(50) DEFAULT NULL, "
            + "`shipping_address` VARCHAR(500) DEFAULT NULL, "
            + "`total_amount` DECIMAL(12,2) DEFAULT NULL, "
            + "`paid_amount` DECIMAL(12,2) DEFAULT 0.00, "
            + "`payment_status` VARCHAR(20) DEFAULT NULL, "
            + "`settlement_time` DATETIME DEFAULT NULL, "
            + "PRIMARY KEY (`id`)"
            + ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin");
        TABLE_FIXES.put("t_factory_shipment",
            "CREATE TABLE IF NOT EXISTS `t_factory_shipment` ("
            + "`id` VARCHAR(36) NOT NULL,"
            + "`shipment_no` VARCHAR(50) NOT NULL,"
            + "`order_id` VARCHAR(36) NOT NULL,"
            + "`order_no` VARCHAR(50) DEFAULT NULL,"
            + "`style_no` VARCHAR(50) DEFAULT NULL,"
            + "`style_name` VARCHAR(200) DEFAULT NULL,"
            + "`factory_id` VARCHAR(36) DEFAULT NULL,"
            + "`factory_name` VARCHAR(100) DEFAULT NULL,"
            + "`ship_quantity` INT NOT NULL DEFAULT 0,"
            + "`ship_time` DATETIME DEFAULT NULL,"
            + "`shipped_by` VARCHAR(36) DEFAULT NULL,"
            + "`shipped_by_name` VARCHAR(50) DEFAULT NULL,"
            + "`tracking_no` VARCHAR(100) DEFAULT NULL,"
            + "`express_company` VARCHAR(100) DEFAULT NULL,"
            + "`ship_method` VARCHAR(32) DEFAULT 'EXPRESS',"
            + "`receive_status` VARCHAR(20) NOT NULL DEFAULT 'pending',"
            + "`receive_time` DATETIME DEFAULT NULL,"
            + "`received_by` VARCHAR(36) DEFAULT NULL,"
            + "`received_by_name` VARCHAR(50) DEFAULT NULL,"
            + "`remark` VARCHAR(500) DEFAULT NULL,"
            + "`tenant_id` BIGINT DEFAULT NULL,"
            + "`creator_id` VARCHAR(36) DEFAULT NULL,"
            + "`creator_name` VARCHAR(50) DEFAULT NULL,"
            + "`create_time` DATETIME DEFAULT NULL,"
            + "`update_time` DATETIME DEFAULT NULL,"
            + "`delete_flag` INT NOT NULL DEFAULT 0,"
            + "PRIMARY KEY (`id`),"
            + "KEY `idx_fs_order_id` (`order_id`),"
            + "KEY `idx_fs_factory_id` (`factory_id`),"
            + "KEY `idx_fs_tenant_status` (`tenant_id`, `receive_status`)"
            + ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin");
        TABLE_FIXES.put("t_factory_shipment_detail",
            "CREATE TABLE IF NOT EXISTS `t_factory_shipment_detail` ("
            + "`id` VARCHAR(64) NOT NULL,"
            + "`shipment_id` VARCHAR(64) NOT NULL,"
            + "`color` VARCHAR(50) NOT NULL DEFAULT '',"
            + "`size_name` VARCHAR(50) NOT NULL DEFAULT '',"
            + "`quantity` INT NOT NULL DEFAULT 0,"
            + "`tenant_id` BIGINT DEFAULT NULL,"
            + "`create_time` DATETIME DEFAULT NULL,"
            + "PRIMARY KEY (`id`),"
            + "KEY `idx_shipment_id` (`shipment_id`),"
            + "KEY `idx_tenant_id` (`tenant_id`)"
            + ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
        TABLE_FIXES.put("t_process_price_adjustment",
            "CREATE TABLE IF NOT EXISTS `t_process_price_adjustment` ("
            + "`id` VARCHAR(36) NOT NULL,"
            + "`tenant_id` BIGINT NOT NULL,"
            + "`order_id` VARCHAR(36) NOT NULL,"
            + "`order_no` VARCHAR(50) DEFAULT NULL,"
            + "`bundle_id` VARCHAR(36) DEFAULT NULL,"
            + "`bundle_no` VARCHAR(50) DEFAULT NULL,"
            + "`process_name` VARCHAR(100) NOT NULL,"
            + "`process_code` VARCHAR(50) DEFAULT NULL,"
            + "`progress_stage` VARCHAR(50) DEFAULT NULL,"
            + "`original_price` DECIMAL(10,2) NOT NULL DEFAULT 0.00,"
            + "`adjusted_price` DECIMAL(10,2) NOT NULL,"
            + "`reason` TEXT NOT NULL,"
            + "`adjusted_by` VARCHAR(36) NOT NULL,"
            + "`adjusted_by_name` VARCHAR(50) DEFAULT NULL,"
            + "`adjusted_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,"
            + "`delete_flag` INT NOT NULL DEFAULT 0,"
            + "`create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,"
            + "`update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,"
            + "PRIMARY KEY (`id`),"
            + "INDEX `idx_ppa_tenant` (`tenant_id`),"
            + "INDEX `idx_ppa_order` (`order_id`),"
            + "INDEX `idx_ppa_order_no` (`order_no`)"
            + ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
        TABLE_FIXES.put("t_ai_job_run_log",
            "CREATE TABLE IF NOT EXISTS `t_ai_job_run_log` ("
            + "`id` BIGINT NOT NULL AUTO_INCREMENT,"
            + "`tenant_id` BIGINT DEFAULT NULL,"
            + "`job_name` VARCHAR(100) DEFAULT NULL,"
            + "`method_name` VARCHAR(100) DEFAULT NULL,"
            + "`start_time` DATETIME DEFAULT NULL,"
            + "`duration_ms` BIGINT DEFAULT NULL,"
            + "`status` VARCHAR(20) DEFAULT NULL,"
            + "`tenant_count` INT DEFAULT NULL,"
            + "`result_summary` VARCHAR(500) DEFAULT NULL,"
            + "`error_message` TEXT DEFAULT NULL,"
            + "`created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,"
            + "PRIMARY KEY (`id`),"
            + "INDEX `idx_ajrl_tenant` (`tenant_id`),"
            + "INDEX `idx_ajrl_job_time` (`job_name`, `start_time`)"
            + ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
        TABLE_FIXES.put("t_sys_notice",
            "CREATE TABLE IF NOT EXISTS `t_sys_notice` ("
            + "`id` BIGINT NOT NULL AUTO_INCREMENT,"
            + "`tenant_id` BIGINT DEFAULT NULL,"
            + "`to_name` VARCHAR(50) DEFAULT NULL,"
            + "`from_name` VARCHAR(50) DEFAULT NULL,"
            + "`order_no` VARCHAR(50) DEFAULT NULL,"
            + "`title` VARCHAR(200) DEFAULT NULL,"
            + "`content` TEXT DEFAULT NULL,"
            + "`notice_type` VARCHAR(50) DEFAULT NULL,"
            + "`is_read` INT NOT NULL DEFAULT 0,"
            + "`created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,"
            + "PRIMARY KEY (`id`),"
            + "INDEX `idx_sn_tenant` (`tenant_id`),"
            + "INDEX `idx_sn_to_name` (`to_name`),"
            + "INDEX `idx_sn_created_at` (`created_at`)"
            + ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
        TABLE_FIXES.put("t_production_process_tracking",
            "CREATE TABLE IF NOT EXISTS `t_production_process_tracking` ("
            + "`id` VARCHAR(64) NOT NULL COMMENT '主键ID',"
            + "`production_order_id` VARCHAR(64) DEFAULT NULL,"
            + "`production_order_no` VARCHAR(64) DEFAULT NULL,"
            + "`cutting_bundle_id` VARCHAR(64) DEFAULT NULL,"
            + "`bundle_no` VARCHAR(50) DEFAULT NULL,"
            + "`sku` VARCHAR(100) DEFAULT NULL,"
            + "`color` VARCHAR(50) DEFAULT NULL,"
            + "`size` VARCHAR(50) DEFAULT NULL,"
            + "`quantity` INT DEFAULT NULL,"
            + "`process_code` VARCHAR(50) DEFAULT NULL,"
            + "`process_name` VARCHAR(100) DEFAULT NULL,"
            + "`process_order` INT DEFAULT NULL,"
            + "`unit_price` DECIMAL(10,4) DEFAULT NULL,"
            + "`scan_status` VARCHAR(20) DEFAULT NULL,"
            + "`scan_time` DATETIME DEFAULT NULL,"
            + "`scan_record_id` VARCHAR(64) DEFAULT NULL,"
            + "`operator_id` VARCHAR(64) DEFAULT NULL,"
            + "`operator_name` VARCHAR(100) DEFAULT NULL,"
            + "`settlement_amount` DECIMAL(12,2) DEFAULT NULL,"
            + "`is_settled` TINYINT(1) DEFAULT 0,"
            + "`settled_at` DATETIME DEFAULT NULL,"
            + "`settled_batch_no` VARCHAR(64) DEFAULT NULL,"
            + "`settled_by` VARCHAR(64) DEFAULT NULL,"
            + "`created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,"
            + "`updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,"
            + "`creator` VARCHAR(64) DEFAULT NULL,"
            + "`updater` VARCHAR(64) DEFAULT NULL,"
            + "`tenant_id` BIGINT DEFAULT NULL,"
            + "PRIMARY KEY (`id`),"
            + "KEY `idx_ppt_order` (`production_order_no`),"
            + "KEY `idx_ppt_bundle` (`cutting_bundle_id`),"
            + "KEY `idx_ppt_tenant` (`tenant_id`)"
            + ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='生产工序追踪表'");
        TABLE_FIXES.put("t_customer_client_user",
            "CREATE TABLE IF NOT EXISTS `t_customer_client_user` ("
            + "`id` VARCHAR(36) NOT NULL COMMENT '主键',"
            + "`customer_id` VARCHAR(36) NOT NULL COMMENT '关联客户ID',"
            + "`tenant_id` BIGINT NOT NULL COMMENT '所属租户ID',"
            + "`username` VARCHAR(100) NOT NULL COMMENT '登录用户名',"
            + "`password_hash` VARCHAR(255) NOT NULL COMMENT '加密后的密码',"
            + "`contact_person` VARCHAR(100) DEFAULT NULL COMMENT '联系人姓名',"
            + "`contact_phone` VARCHAR(50) DEFAULT NULL COMMENT '联系电话',"
            + "`contact_email` VARCHAR(100) DEFAULT NULL COMMENT '联系邮箱',"
            + "`status` VARCHAR(20) DEFAULT 'ACTIVE' COMMENT '状态：ACTIVE/INACTIVE',"
            + "`last_login_time` DATETIME DEFAULT NULL COMMENT '最后登录时间',"
            + "`create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',"
            + "`update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',"
            + "`delete_flag` INT DEFAULT 0 COMMENT '软删除标志：0正常1已删除',"
            + "PRIMARY KEY (`id`),"
            + "UNIQUE KEY `idx_ccu_username` (`username`),"
            + "KEY `idx_ccu_customer_id` (`customer_id`),"
            + "KEY `idx_ccu_tenant_id` (`tenant_id`)"
            + ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='客户用户表'");
        TABLE_FIXES.put("t_supplier_user",
            "CREATE TABLE IF NOT EXISTS `t_supplier_user` ("
            + "`id` VARCHAR(36) NOT NULL COMMENT '主键',"
            + "`supplier_id` VARCHAR(36) NOT NULL COMMENT '关联供应商ID',"
            + "`tenant_id` BIGINT NOT NULL COMMENT '所属租户ID',"
            + "`username` VARCHAR(100) NOT NULL COMMENT '登录用户名',"
            + "`password_hash` VARCHAR(255) NOT NULL COMMENT '加密后的密码',"
            + "`contact_person` VARCHAR(100) DEFAULT NULL COMMENT '联系人姓名',"
            + "`contact_phone` VARCHAR(50) DEFAULT NULL COMMENT '联系电话',"
            + "`contact_email` VARCHAR(100) DEFAULT NULL COMMENT '联系邮箱',"
            + "`status` VARCHAR(20) DEFAULT 'ACTIVE' COMMENT '状态：ACTIVE/INACTIVE',"
            + "`last_login_time` DATETIME DEFAULT NULL COMMENT '最后登录时间',"
            + "`create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',"
            + "`update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',"
            + "`delete_flag` INT DEFAULT 0 COMMENT '软删除标志：0正常1已删除',"
            + "PRIMARY KEY (`id`),"
            + "UNIQUE KEY `idx_su_username` (`username`),"
            + "KEY `idx_su_supplier_id` (`supplier_id`),"
            + "KEY `idx_su_tenant_id` (`tenant_id`)"
            + ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='供应商用户表'");
        TABLE_FIXES.put("t_ai_plan",
            "CREATE TABLE IF NOT EXISTS `t_ai_plan` ("
            + "`id` BIGINT NOT NULL AUTO_INCREMENT,"
            + "`plan_uid` VARCHAR(64) NOT NULL,"
            + "`tenant_id` BIGINT DEFAULT NULL,"
            + "`user_id` VARCHAR(64) DEFAULT NULL,"
            + "`user_name` VARCHAR(100) DEFAULT NULL,"
            + "`session_id` VARCHAR(64) DEFAULT NULL,"
            + "`goal` TEXT,"
            + "`plan_json` LONGTEXT,"
            + "`total_steps` INT DEFAULT 0,"
            + "`completed_steps` INT DEFAULT 0,"
            + "`current_step` INT DEFAULT 0,"
            + "`status` VARCHAR(32) DEFAULT 'PLANNING',"
            + "`visibility` VARCHAR(32) DEFAULT 'TENANT',"
            + "`final_result` LONGTEXT,"
            + "`error_message` TEXT,"
            + "`total_tokens` INT DEFAULT 0,"
            + "`total_duration_ms` BIGINT DEFAULT 0,"
            + "`replan_count` INT DEFAULT 0,"
            + "`trace_id` VARCHAR(128) DEFAULT NULL,"
            + "`create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,"
            + "`update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,"
            + "PRIMARY KEY (`id`),"
            + "UNIQUE KEY `uk_ai_plan_uid` (`plan_uid`),"
            + "KEY `idx_ai_plan_tenant` (`tenant_id`,`status`),"
            + "KEY `idx_ai_plan_session` (`session_id`)"
            + ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI Plan-and-Execute 主表'");
        TABLE_FIXES.put("t_ai_process_reward",
            "CREATE TABLE IF NOT EXISTS `t_ai_process_reward` ("
            + "`id` BIGINT NOT NULL AUTO_INCREMENT,"
            + "`tenant_id` BIGINT DEFAULT NULL,"
            + "`session_id` VARCHAR(64) DEFAULT NULL,"
            + "`plan_id` BIGINT DEFAULT NULL,"
            + "`step_index` INT DEFAULT NULL,"
            + "`tool_name` VARCHAR(100) DEFAULT NULL,"
            + "`tool_input` TEXT,"
            + "`tool_output_summary` TEXT,"
            + "`score` INT DEFAULT 0,"
            + "`score_reason` VARCHAR(500) DEFAULT NULL,"
            + "`score_source` VARCHAR(32) DEFAULT 'AUTO',"
            + "`outcome` VARCHAR(32) DEFAULT NULL,"
            + "`duration_ms` INT DEFAULT NULL,"
            + "`token_cost` INT DEFAULT NULL,"
            + "`scene` VARCHAR(64) DEFAULT NULL,"
            + "`create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,"
            + "PRIMARY KEY (`id`),"
            + "KEY `idx_prm_tool_time` (`tool_name`,`create_time`),"
            + "KEY `idx_prm_tenant_time` (`tenant_id`,`create_time`),"
            + "KEY `idx_prm_plan` (`plan_id`)"
            + ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI 过程奖励 PRM 评分'");
        TABLE_FIXES.put("t_ai_long_memory",
            "CREATE TABLE IF NOT EXISTS `t_ai_long_memory` ("
            + "`id` BIGINT NOT NULL AUTO_INCREMENT,"
            + "`memory_uid` VARCHAR(64) NOT NULL,"
            + "`tenant_id` BIGINT DEFAULT NULL,"
            + "`scope` VARCHAR(32) DEFAULT 'TENANT',"
            + "`layer` VARCHAR(32) DEFAULT 'FACT',"
            + "`subject_type` VARCHAR(64) DEFAULT NULL,"
            + "`subject_id` VARCHAR(64) DEFAULT NULL,"
            + "`subject_name` VARCHAR(200) DEFAULT NULL,"
            + "`content` TEXT,"
            + "`embedding_id` VARCHAR(128) DEFAULT NULL,"
            + "`confidence` DECIMAL(5,2) DEFAULT 60,"
            + "`hit_count` INT DEFAULT 0,"
            + "`last_hit_time` DATETIME DEFAULT NULL,"
            + "`source_session_id` VARCHAR(64) DEFAULT NULL,"
            + "`source_user_id` VARCHAR(64) DEFAULT NULL,"
            + "`verified` INT DEFAULT 0,"
            + "`expire_time` DATETIME DEFAULT NULL,"
            + "`delete_flag` INT DEFAULT 0,"
            + "`create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,"
            + "`update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,"
            + "PRIMARY KEY (`id`),"
            + "UNIQUE KEY `uk_ai_memory_uid` (`memory_uid`),"
            + "KEY `idx_ai_mem_subject` (`subject_type`,`subject_id`),"
            + "KEY `idx_ai_mem_scope_tenant` (`scope`,`tenant_id`)"
            + ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI 长期记忆三层架构'");
        TABLE_FIXES.put("t_ai_decision_card",
            "CREATE TABLE IF NOT EXISTS `t_ai_decision_card` ("
            + "`id` BIGINT NOT NULL AUTO_INCREMENT,"
            + "`card_uid` VARCHAR(64) NOT NULL,"
            + "`tenant_id` BIGINT DEFAULT NULL,"
            + "`user_id` VARCHAR(64) DEFAULT NULL,"
            + "`session_id` VARCHAR(64) DEFAULT NULL,"
            + "`plan_id` BIGINT DEFAULT NULL,"
            + "`scene` VARCHAR(64) DEFAULT NULL,"
            + "`question` TEXT,"
            + "`recommendation` LONGTEXT,"
            + "`data_evidence_json` LONGTEXT,"
            + "`reasoning_path_json` LONGTEXT,"
            + "`uncertainty_json` LONGTEXT,"
            + "`confidence` DECIMAL(5,2) DEFAULT NULL,"
            + "`risk_level` VARCHAR(20) DEFAULT 'MEDIUM',"
            + "`trace_id` VARCHAR(128) DEFAULT NULL,"
            + "`adopted` INT DEFAULT 0,"
            + "`adoption_time` DATETIME DEFAULT NULL,"
            + "`adoption_reason` VARCHAR(500) DEFAULT NULL,"
            + "`feedback_score` INT DEFAULT NULL,"
            + "`create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,"
            + "`update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,"
            + "PRIMARY KEY (`id`),"
            + "UNIQUE KEY `uk_ai_card_uid` (`card_uid`),"
            + "KEY `idx_ai_card_tenant_time` (`tenant_id`,`create_time`),"
            + "KEY `idx_ai_card_scene` (`scene`,`adopted`)"
            + ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI 可解释决策卡'");
        TABLE_FIXES.put("t_ai_patrol_action",
            "CREATE TABLE IF NOT EXISTS `t_ai_patrol_action` ("
            + "`id` BIGINT NOT NULL AUTO_INCREMENT,"
            + "`action_uid` VARCHAR(64) NOT NULL,"
            + "`tenant_id` BIGINT DEFAULT NULL,"
            + "`patrol_source` VARCHAR(64) DEFAULT NULL,"
            + "`detected_issue` TEXT,"
            + "`issue_type` VARCHAR(64) DEFAULT NULL,"
            + "`issue_severity` VARCHAR(20) DEFAULT 'MEDIUM',"
            + "`target_type` VARCHAR(64) DEFAULT NULL,"
            + "`target_id` VARCHAR(64) DEFAULT NULL,"
            + "`suggested_action_json` LONGTEXT,"
            + "`confidence` DECIMAL(5,2) DEFAULT NULL,"
            + "`risk_level` VARCHAR(32) DEFAULT 'NEED_APPROVAL',"
            + "`status` VARCHAR(32) DEFAULT 'PENDING',"
            + "`auto_executed` INT DEFAULT 0,"
            + "`execution_result` TEXT,"
            + "`execution_time` DATETIME DEFAULT NULL,"
            + "`approver_id` VARCHAR(64) DEFAULT NULL,"
            + "`approver_name` VARCHAR(100) DEFAULT NULL,"
            + "`approval_time` DATETIME DEFAULT NULL,"
            + "`approval_remark` VARCHAR(500) DEFAULT NULL,"
            + "`close_time` DATETIME DEFAULT NULL,"
            + "`mttr_minutes` INT DEFAULT NULL,"
            + "`linked_audit_id` VARCHAR(64) DEFAULT NULL,"
            + "`create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,"
            + "`update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,"
            + "PRIMARY KEY (`id`),"
            + "UNIQUE KEY `uk_ai_patrol_uid` (`action_uid`),"
            + "KEY `idx_ai_patrol_tenant_status` (`tenant_id`,`status`),"
            + "KEY `idx_ai_patrol_issue` (`issue_type`,`issue_severity`)"
            + ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI 主动巡检闭环'");
        TABLE_FIXES.put("t_ai_platform_aggregate",
            "CREATE TABLE IF NOT EXISTS `t_ai_platform_aggregate` ("
            + "`id` BIGINT NOT NULL AUTO_INCREMENT,"
            + "`metric_key` VARCHAR(100) NOT NULL,"
            + "`metric_dim` VARCHAR(200) DEFAULT NULL,"
            + "`period` VARCHAR(20) DEFAULT 'DAY',"
            + "`period_start` DATETIME DEFAULT NULL,"
            + "`period_end` DATETIME DEFAULT NULL,"
            + "`tenant_id` BIGINT DEFAULT NULL,"
            + "`metric_value` DECIMAL(18,4) DEFAULT NULL,"
            + "`metric_count` BIGINT DEFAULT NULL,"
            + "`metric_min` DECIMAL(18,4) DEFAULT NULL,"
            + "`metric_max` DECIMAL(18,4) DEFAULT NULL,"
            + "`metric_p50` DECIMAL(18,4) DEFAULT NULL,"
            + "`metric_p90` DECIMAL(18,4) DEFAULT NULL,"
            + "`extra_json` TEXT,"
            + "`create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,"
            + "PRIMARY KEY (`id`),"
            + "KEY `idx_ai_agg_metric_period` (`metric_key`,`period`,`period_start`),"
            + "KEY `idx_ai_agg_tenant` (`tenant_id`,`metric_key`)"
            + ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI 平台级跨租户聚合（仅超管）'");
        TABLE_FIXES.put("t_xiaoyun_daily_insight",
            "CREATE TABLE IF NOT EXISTS `t_xiaoyun_daily_insight` ("
            + "`id` VARCHAR(64) NOT NULL,"
            + "`tenant_id` BIGINT NOT NULL,"
            + "`insight_date` DATE NOT NULL,"
            + "`scene` VARCHAR(50) NOT NULL,"
            + "`severity` VARCHAR(20) DEFAULT 'info',"
            + "`title` VARCHAR(200) NOT NULL,"
            + "`content` TEXT DEFAULT NULL,"
            + "`card_json` TEXT DEFAULT NULL,"
            + "`action_url` VARCHAR(500) DEFAULT NULL,"
            + "`auto_todo_id` VARCHAR(64) DEFAULT NULL,"
            + "`read_flag` TINYINT NOT NULL DEFAULT 0,"
            + "`dismissed` TINYINT NOT NULL DEFAULT 0,"
            + "`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,"
            + "PRIMARY KEY (`id`),"
            + "INDEX `idx_insight_tenant_date` (`tenant_id`, `insight_date`, `read_flag`),"
            + "INDEX `idx_insight_created` (`created_at`)"
            + ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='小云每日洞察推送'");
        TABLE_FIXES.put("t_xiaoyun_evolution_log",
            "CREATE TABLE IF NOT EXISTS `t_xiaoyun_evolution_log` ("
            + "`id` VARCHAR(64) NOT NULL PRIMARY KEY,"
            + "`category` VARCHAR(32) NOT NULL,"
            + "`description` TEXT DEFAULT NULL,"
            + "`before_state` TEXT DEFAULT NULL,"
            + "`after_state` TEXT DEFAULT NULL,"
            + "`confidence` DECIMAL(5,2) DEFAULT 0,"
            + "`source` VARCHAR(64) DEFAULT NULL,"
            + "`status` VARCHAR(32) NOT NULL DEFAULT 'PROPOSED',"
            + "`test_report` TEXT DEFAULT NULL,"
            + "`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,"
            + "`updated_at` DATETIME DEFAULT NULL,"
            + "INDEX `idx_evo_status` (`status`),"
            + "INDEX `idx_evo_created` (`created_at`)"
            + ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='小云自进化日志表'");
        TABLE_FIXES.put("t_xiaoyun_prompt_version",
            "CREATE TABLE IF NOT EXISTS `t_xiaoyun_prompt_version` ("
            + "`id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,"
            + "`proposal_id` VARCHAR(64) NOT NULL,"
            + "`category` VARCHAR(32) DEFAULT NULL,"
            + "`before_prompt` TEXT DEFAULT NULL,"
            + "`after_prompt` TEXT DEFAULT NULL,"
            + "`status` VARCHAR(32) NOT NULL DEFAULT 'PENDING_REVIEW',"
            + "`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,"
            + "INDEX `idx_prompt_proposal` (`proposal_id`),"
            + "INDEX `idx_prompt_status` (`status`)"
            + ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='小云Prompt版本管理表'");
        TABLE_FIXES.put("t_xiaoyun_param_version",
            "CREATE TABLE IF NOT EXISTS `t_xiaoyun_param_version` ("
            + "`id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,"
            + "`proposal_id` VARCHAR(64) NOT NULL,"
            + "`param_key` VARCHAR(128) DEFAULT NULL,"
            + "`before_value` TEXT DEFAULT NULL,"
            + "`after_value` TEXT DEFAULT NULL,"
            + "`status` VARCHAR(32) NOT NULL DEFAULT 'PENDING_REVIEW',"
            + "`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,"
            + "INDEX `idx_param_proposal` (`proposal_id`),"
            + "INDEX `idx_param_status` (`status`)"
            + ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='小云参数版本管理表'");
        TABLE_FIXES.put("t_ai_skill_node",
            "CREATE TABLE IF NOT EXISTS `t_ai_skill_node` ("
            + "`id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,"
            + "`tenant_id` BIGINT DEFAULT NULL,"
            + "`skill_name` VARCHAR(200) NOT NULL,"
            + "`skill_domain` VARCHAR(50) DEFAULT NULL,"
            + "`trigger_pattern` VARCHAR(500) DEFAULT NULL,"
            + "`tool_chain` TEXT DEFAULT NULL,"
            + "`success_count` INT NOT NULL DEFAULT 0,"
            + "`failure_count` INT NOT NULL DEFAULT 0,"
            + "`avg_score` DECIMAL(5,2) NOT NULL DEFAULT 0,"
            + "`last_activated_at` DATETIME DEFAULT NULL,"
            + "`parent_skill_id` BIGINT DEFAULT NULL,"
            + "`embedding_id` VARCHAR(100) DEFAULT NULL,"
            + "`delete_flag` TINYINT NOT NULL DEFAULT 0,"
            + "`create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,"
            + "`update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,"
            + "INDEX `idx_tenant_domain` (`tenant_id`, `skill_domain`),"
            + "INDEX `idx_skill_name` (`skill_name`(100)),"
            + "INDEX `idx_parent_skill_id` (`parent_skill_id`)"
            + ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");

        TABLE_FIXES.put("t_secondary_process",
            "CREATE TABLE IF NOT EXISTS `t_secondary_process` ("
            + "`id` BIGINT NOT NULL AUTO_INCREMENT,"
            + "`style_id` BIGINT DEFAULT NULL COMMENT '款式ID',"
            + "`style_no` VARCHAR(100) DEFAULT NULL COMMENT '款号',"
            + "`process_type` VARCHAR(50) DEFAULT NULL COMMENT '工艺类型',"
            + "`process_name` VARCHAR(100) DEFAULT NULL COMMENT '工艺名称',"
            + "`description` VARCHAR(255) DEFAULT NULL COMMENT '工艺描述',"
            + "`quantity` INT DEFAULT NULL COMMENT '数量',"
            + "`unit_price` DECIMAL(15,2) DEFAULT NULL COMMENT '单价',"
            + "`total_price` DECIMAL(15,2) DEFAULT NULL COMMENT '总价',"
            + "`factory_name` VARCHAR(100) DEFAULT NULL COMMENT '工厂名称',"
            + "`factory_id` VARCHAR(64) DEFAULT NULL COMMENT '工厂ID',"
            + "`factory_contact_person` VARCHAR(100) DEFAULT NULL COMMENT '工厂联系人',"
            + "`factory_contact_phone` VARCHAR(50) DEFAULT NULL COMMENT '工厂联系电话',"
            + "`assignee` VARCHAR(100) DEFAULT NULL COMMENT '领取人',"
            + "`assignee_id` VARCHAR(64) DEFAULT NULL COMMENT '领取人ID',"
            + "`operator_id` VARCHAR(64) DEFAULT NULL COMMENT '操作员ID',"
            + "`operator_name` VARCHAR(100) DEFAULT NULL COMMENT '操作员姓名',"
            + "`creator_id` VARCHAR(64) DEFAULT NULL COMMENT '创建人ID',"
            + "`creator_name` VARCHAR(100) DEFAULT NULL COMMENT '创建人姓名',"
            + "`status` VARCHAR(20) DEFAULT NULL COMMENT '状态',"
            + "`approval_status` VARCHAR(20) DEFAULT NULL COMMENT '审批状态',"
            + "`approved_by_id` VARCHAR(64) DEFAULT NULL COMMENT '审批人ID',"
            + "`approved_by_name` VARCHAR(100) DEFAULT NULL COMMENT '审批人姓名',"
            + "`approved_time` DATETIME DEFAULT NULL COMMENT '审批时间',"
            + "`completed_time` DATETIME DEFAULT NULL COMMENT '完成时间',"
            + "`images` TEXT DEFAULT NULL COMMENT '图片',"
            + "`attachments` TEXT DEFAULT NULL COMMENT '附件',"
            + "`remark` VARCHAR(500) DEFAULT NULL COMMENT '备注',"
            + "`tenant_id` BIGINT DEFAULT NULL COMMENT '租户ID',"
            + "`delete_flag` INT NOT NULL DEFAULT 0 COMMENT '删除标记',"
            + "`created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',"
            + "`updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',"
            + "PRIMARY KEY (`id`),"
            + "INDEX `idx_style_id` (`style_id`),"
            + "INDEX `idx_tenant_id` (`tenant_id`)"
            + ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='二次工艺表'");
        // 2026-04-28：补三张高频缺表自愈，避免云端 Flyway 漏跑或镜像滞后导致整链路 500
        // 触发场景：/api/finance/wage-settlement-feedback/list 等接口报 500，
        // MyBatis "best guess" 误指向 BillAggregationMapper / IntegrationChannelConfigMapper。
        TABLE_FIXES.put("t_wage_settlement_feedback",
            "CREATE TABLE IF NOT EXISTS `t_wage_settlement_feedback` ("
            + "`id` VARCHAR(36) NOT NULL,"
            + "`settlement_id` VARCHAR(36) DEFAULT NULL COMMENT '关联工资结算单ID',"
            + "`operator_id` VARCHAR(36) DEFAULT NULL COMMENT '反馈人ID',"
            + "`operator_name` VARCHAR(64) DEFAULT NULL COMMENT '反馈人姓名',"
            + "`feedback_type` VARCHAR(20) NOT NULL COMMENT '反馈类型',"
            + "`feedback_content` TEXT DEFAULT NULL COMMENT '反馈内容',"
            + "`status` VARCHAR(20) NOT NULL DEFAULT 'PENDING' COMMENT '状态',"
            + "`resolve_remark` VARCHAR(500) DEFAULT NULL COMMENT '处理备注',"
            + "`resolver_id` VARCHAR(36) DEFAULT NULL COMMENT '处理人ID',"
            + "`resolver_name` VARCHAR(64) DEFAULT NULL COMMENT '处理人姓名',"
            + "`resolve_time` DATETIME DEFAULT NULL COMMENT '处理时间',"
            + "`tenant_id` BIGINT DEFAULT NULL,"
            + "`create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,"
            + "`update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,"
            + "PRIMARY KEY (`id`),"
            + "KEY `idx_wsf_settlement_id` (`settlement_id`),"
            + "KEY `idx_wsf_operator_id` (`operator_id`),"
            + "KEY `idx_wsf_tenant_id` (`tenant_id`),"
            + "KEY `idx_wsf_status` (`status`)"
            + ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='工资结算反馈'");
        TABLE_FIXES.put("t_bill_aggregation",
            "CREATE TABLE IF NOT EXISTS `t_bill_aggregation` ("
            + "`id` VARCHAR(36) NOT NULL,"
            + "`bill_no` VARCHAR(64) DEFAULT NULL,"
            + "`bill_type` VARCHAR(32) DEFAULT NULL,"
            + "`bill_category` VARCHAR(32) DEFAULT NULL,"
            + "`source_type` VARCHAR(32) DEFAULT NULL,"
            + "`source_id` VARCHAR(64) DEFAULT NULL,"
            + "`source_no` VARCHAR(64) DEFAULT NULL,"
            + "`counterparty_type` VARCHAR(32) DEFAULT NULL,"
            + "`counterparty_id` VARCHAR(64) DEFAULT NULL,"
            + "`counterparty_name` VARCHAR(200) DEFAULT NULL,"
            + "`order_id` VARCHAR(64) DEFAULT NULL,"
            + "`order_no` VARCHAR(64) DEFAULT NULL,"
            + "`style_no` VARCHAR(64) DEFAULT NULL,"
            + "`amount` DECIMAL(14,2) DEFAULT NULL,"
            + "`settled_amount` DECIMAL(14,2) DEFAULT NULL,"
            + "`status` VARCHAR(32) DEFAULT NULL,"
            + "`settlement_month` VARCHAR(16) DEFAULT NULL,"
            + "`remark` VARCHAR(512) DEFAULT NULL,"
            + "`confirmed_by_id` VARCHAR(64) DEFAULT NULL,"
            + "`confirmed_by_name` VARCHAR(100) DEFAULT NULL,"
            + "`confirmed_at` DATETIME DEFAULT NULL,"
            + "`settled_by_id` VARCHAR(64) DEFAULT NULL,"
            + "`settled_by_name` VARCHAR(100) DEFAULT NULL,"
            + "`settled_at` DATETIME DEFAULT NULL,"
            + "`creator_id` VARCHAR(64) DEFAULT NULL,"
            + "`creator_name` VARCHAR(100) DEFAULT NULL,"
            + "`create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,"
            + "`update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,"
            + "`tenant_id` BIGINT DEFAULT NULL,"
            + "`delete_flag` INT NOT NULL DEFAULT 0,"
            + "PRIMARY KEY (`id`),"
            + "UNIQUE KEY `uk_bill_no` (`bill_no`),"
            + "UNIQUE KEY `uk_source` (`source_type`, `source_id`, `tenant_id`),"
            + "KEY `idx_ba_tenant_status` (`tenant_id`, `status`),"
            + "KEY `idx_ba_counterparty` (`counterparty_type`, `counterparty_id`),"
            + "KEY `idx_ba_order_no` (`order_no`)"
            + ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='账单聚合表'");
        TABLE_FIXES.put("t_integration_channel_config",
            "CREATE TABLE IF NOT EXISTS `t_integration_channel_config` ("
            + "`id` BIGINT AUTO_INCREMENT,"
            + "`tenant_id` BIGINT NOT NULL,"
            + "`channel_code` VARCHAR(32) NOT NULL,"
            + "`enabled` TINYINT(1) NOT NULL DEFAULT 0,"
            + "`app_id` VARCHAR(128) DEFAULT NULL,"
            + "`app_secret` VARCHAR(512) DEFAULT NULL,"
            + "`private_key` TEXT DEFAULT NULL,"
            + "`public_key` TEXT DEFAULT NULL,"
            + "`notify_url` VARCHAR(512) DEFAULT NULL,"
            + "`extra_config` JSON DEFAULT NULL,"
            + "`create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,"
            + "`update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,"
            + "`delete_flag` TINYINT(1) NOT NULL DEFAULT 0,"
            + "PRIMARY KEY (`id`),"
            + "UNIQUE KEY `uk_tenant_channel` (`tenant_id`, `channel_code`)"
            + ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='集成渠道配置'");
        TABLE_FIXES.put("t_material_quality_issue",
            "CREATE TABLE IF NOT EXISTS `t_material_quality_issue` ("
            + "`id` VARCHAR(64) NOT NULL,"
            + "`issue_no` VARCHAR(64) NOT NULL,"
            + "`purchase_id` VARCHAR(64) NOT NULL,"
            + "`purchase_no` VARCHAR(64) DEFAULT NULL,"
            + "`order_id` VARCHAR(64) DEFAULT NULL,"
            + "`order_no` VARCHAR(64) DEFAULT NULL,"
            + "`style_id` VARCHAR(64) DEFAULT NULL,"
            + "`style_no` VARCHAR(64) DEFAULT NULL,"
            + "`supplier_id` VARCHAR(64) DEFAULT NULL,"
            + "`supplier_name` VARCHAR(128) DEFAULT NULL,"
            + "`material_id` VARCHAR(64) DEFAULT NULL,"
            + "`material_code` VARCHAR(64) DEFAULT NULL,"
            + "`material_name` VARCHAR(128) DEFAULT NULL,"
            + "`material_type` VARCHAR(64) DEFAULT NULL,"
            + "`issue_quantity` INT DEFAULT 0,"
            + "`issue_type` VARCHAR(32) DEFAULT NULL,"
            + "`severity` VARCHAR(32) DEFAULT NULL,"
            + "`disposition` VARCHAR(32) DEFAULT NULL,"
            + "`status` VARCHAR(32) DEFAULT NULL,"
            + "`evidence_image_urls` TEXT,"
            + "`remark` VARCHAR(500) DEFAULT NULL,"
            + "`resolution_remark` VARCHAR(500) DEFAULT NULL,"
            + "`related_purchase_id` VARCHAR(64) DEFAULT NULL,"
            + "`related_purchase_no` VARCHAR(64) DEFAULT NULL,"
            + "`deduction_amount` DECIMAL(18,2) DEFAULT NULL,"
            + "`reporter_id` VARCHAR(64) DEFAULT NULL,"
            + "`reporter_name` VARCHAR(64) DEFAULT NULL,"
            + "`resolver_id` VARCHAR(64) DEFAULT NULL,"
            + "`resolver_name` VARCHAR(64) DEFAULT NULL,"
            + "`resolved_time` DATETIME DEFAULT NULL,"
            + "`tenant_id` BIGINT DEFAULT NULL,"
            + "`create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,"
            + "`update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,"
            + "`delete_flag` TINYINT(1) DEFAULT 0,"
            + "PRIMARY KEY (`id`),"
            + "UNIQUE KEY `uk_material_quality_issue_no` (`issue_no`),"
            + "KEY `idx_material_quality_issue_purchase` (`purchase_id`),"
            + "KEY `idx_material_quality_issue_tenant_status` (`tenant_id`, `status`)"
            + ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='物料质量问题'");
        TABLE_FIXES.put("t_agent_card",
            "CREATE TABLE IF NOT EXISTS `t_agent_card` ("
            + "`id` BIGINT NOT NULL AUTO_INCREMENT,"
            + "`tenant_id` BIGINT NOT NULL DEFAULT 0,"
            + "`agent_id` VARCHAR(128) NOT NULL,"
            + "`agent_name` VARCHAR(256) DEFAULT NULL,"
            + "`description` TEXT DEFAULT NULL,"
            + "`skills_json` TEXT DEFAULT NULL,"
            + "`input_types_json` TEXT DEFAULT NULL,"
            + "`output_types_json` TEXT DEFAULT NULL,"
            + "`endpoint_url` VARCHAR(500) DEFAULT NULL,"
            + "`protocol` VARCHAR(32) DEFAULT 'A2A',"
            + "`status` VARCHAR(32) DEFAULT 'ACTIVE',"
            + "`registered_at` DATETIME DEFAULT CURRENT_TIMESTAMP,"
            + "`last_heartbeat` DATETIME DEFAULT NULL,"
            + "PRIMARY KEY (`id`),"
            + "UNIQUE KEY `uk_tenant_agent_id` (`tenant_id`, `agent_id`),"
            + "KEY `idx_ac_status` (`status`)"
            + ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='A2A Agent卡片注册表'");
        TABLE_FIXES.put("t_agent_memory_core",
            "CREATE TABLE IF NOT EXISTS `t_agent_memory_core` ("
            + "`id` BIGINT NOT NULL AUTO_INCREMENT,"
            + "`tenant_id` BIGINT NOT NULL,"
            + "`session_id` VARCHAR(64) DEFAULT NULL,"
            + "`key` VARCHAR(256) NOT NULL,"
            + "`value` TEXT NOT NULL,"
            + "`category` VARCHAR(64) DEFAULT 'general',"
            + "`importance` INT DEFAULT 50,"
            + "`created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,"
            + "`updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,"
            + "PRIMARY KEY (`id`),"
            + "UNIQUE KEY `uk_tenant_session_key` (`tenant_id`, `session_id`, `key`),"
            + "KEY `idx_amc_tenant_category` (`tenant_id`, `category`)"
            + ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Agent核心记忆表'");
        TABLE_FIXES.put("t_agent_memory_archival",
            "CREATE TABLE IF NOT EXISTS `t_agent_memory_archival` ("
            + "`id` BIGINT NOT NULL AUTO_INCREMENT,"
            + "`tenant_id` BIGINT NOT NULL,"
            + "`session_id` VARCHAR(64) DEFAULT NULL,"
            + "`content` TEXT NOT NULL,"
            + "`summary` VARCHAR(500) DEFAULT NULL,"
            + "`category` VARCHAR(64) DEFAULT 'general',"
            + "`importance` INT DEFAULT 50,"
            + "`weight` DOUBLE DEFAULT 1.0,"
            + "`last_accessed_at` DATETIME DEFAULT CURRENT_TIMESTAMP,"
            + "`created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,"
            + "PRIMARY KEY (`id`),"
            + "KEY `idx_ama_tenant_category` (`tenant_id`, `category`),"
            + "KEY `idx_ama_tenant_weight` (`tenant_id`, `weight`)"
            + ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Agent归档记忆表'");
        TABLE_FIXES.put("t_kg_synonym",
            "CREATE TABLE IF NOT EXISTS `t_kg_synonym` ("
            + "`id` BIGINT NOT NULL AUTO_INCREMENT,"
            + "`tenant_id` BIGINT NOT NULL DEFAULT 0,"
            + "`word` VARCHAR(128) NOT NULL,"
            + "`canonical_entity` VARCHAR(256) NOT NULL,"
            + "`entity_type` VARCHAR(64) DEFAULT NULL,"
            + "`created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,"
            + "PRIMARY KEY (`id`),"
            + "UNIQUE KEY `uk_tenant_word` (`tenant_id`, `word`),"
            + "KEY `idx_kgs_entity` (`tenant_id`, `canonical_entity`)"
            + ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='知识图谱同义词映射表'");
        TABLE_FIXES.put("t_nl_query_log",
            "CREATE TABLE IF NOT EXISTS `t_nl_query_log` ("
            + "`id` BIGINT NOT NULL AUTO_INCREMENT,"
            + "`tenant_id` BIGINT NOT NULL DEFAULT 0,"
            + "`user_id` VARCHAR(64) DEFAULT NULL,"
            + "`question` TEXT NOT NULL,"
            + "`detected_intent` VARCHAR(128) DEFAULT NULL,"
            + "`confidence` DOUBLE DEFAULT 0,"
            + "`handler_type` VARCHAR(64) DEFAULT NULL,"
            + "`user_feedback` VARCHAR(20) DEFAULT NULL,"
            + "`correct_intent` VARCHAR(128) DEFAULT NULL,"
            + "`response_time_ms` INT DEFAULT NULL,"
            + "`created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,"
            + "PRIMARY KEY (`id`),"
            + "KEY `idx_nlq_tenant_time` (`tenant_id`, `created_at`),"
            + "KEY `idx_nlq_intent` (`detected_intent`)"
            + ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='自然语言查询日志表'");
        TABLE_FIXES.put("t_collaboration_task",
            "CREATE TABLE IF NOT EXISTS `t_collaboration_task` ("
            + "`id` BIGINT NOT NULL AUTO_INCREMENT,"
            + "`tenant_id` BIGINT NOT NULL,"
            + "`order_no` VARCHAR(100) DEFAULT NULL,"
            + "`target_role` VARCHAR(64) DEFAULT NULL,"
            + "`current_stage` VARCHAR(64) DEFAULT NULL,"
            + "`next_step` VARCHAR(256) DEFAULT NULL,"
            + "`instruction` TEXT DEFAULT NULL,"
            + "`due_hint` VARCHAR(128) DEFAULT NULL,"
            + "`dispatch_response_json` TEXT DEFAULT NULL,"
            + "`updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,"
            + "`due_at` DATETIME DEFAULT NULL,"
            + "`overdue` TINYINT(1) DEFAULT 0,"
            + "`created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,"
            + "PRIMARY KEY (`id`),"
            + "KEY `idx_ct_tenant_order` (`tenant_id`, `order_no`),"
            + "KEY `idx_ct_tenant_role` (`tenant_id`, `target_role`)"
            + ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='协同任务持久化表'");
        TABLE_FIXES.put("t_ai_cost_tracking",
            "CREATE TABLE IF NOT EXISTS `t_ai_cost_tracking` ("
            + "`id` BIGINT NOT NULL AUTO_INCREMENT,"
            + "`tenant_id` BIGINT NOT NULL DEFAULT 0,"
            + "`scene` VARCHAR(100) DEFAULT NULL,"
            + "`provider` VARCHAR(50) DEFAULT NULL,"
            + "`model` VARCHAR(100) DEFAULT NULL,"
            + "`prompt_tokens` INT DEFAULT 0,"
            + "`completion_tokens` INT DEFAULT 0,"
            + "`total_tokens` INT DEFAULT 0,"
            + "`estimated_cost` DECIMAL(10,6) DEFAULT 0,"
            + "`latency_ms` INT DEFAULT NULL,"
            + "`user_id` VARCHAR(64) DEFAULT NULL,"
            + "`trace_id` VARCHAR(64) DEFAULT NULL,"
            + "`created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,"
            + "PRIMARY KEY (`id`),"
            + "KEY `idx_act_tenant_time` (`tenant_id`, `created_at`),"
            + "KEY `idx_act_provider` (`provider`, `model`)"
            + ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI推理成本追踪表'");
        TABLE_FIXES.put("t_ai_operation_audit_record",
            "CREATE TABLE IF NOT EXISTS `t_ai_operation_audit_record` ("
            + "`id` BIGINT NOT NULL AUTO_INCREMENT,"
            + "`tenant_id` BIGINT NOT NULL DEFAULT 0,"
            + "`operation_type` VARCHAR(64) DEFAULT NULL,"
            + "`scene` VARCHAR(100) DEFAULT NULL,"
            + "`provider` VARCHAR(50) DEFAULT NULL,"
            + "`model` VARCHAR(100) DEFAULT NULL,"
            + "`input_summary` TEXT DEFAULT NULL,"
            + "`output_summary` TEXT DEFAULT NULL,"
            + "`tool_calls_json` TEXT DEFAULT NULL,"
            + "`risk_level` VARCHAR(20) DEFAULT 'LOW',"
            + "`pending_review` TINYINT(1) DEFAULT 0,"
            + "`user_id` VARCHAR(64) DEFAULT NULL,"
            + "`duration_ms` BIGINT DEFAULT NULL,"
            + "`created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,"
            + "PRIMARY KEY (`id`),"
            + "KEY `idx_aoar_tenant_time` (`tenant_id`, `created_at`),"
            + "KEY `idx_aoar_pending` (`pending_review`, `tenant_id`)"
            + ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI操作审计记录表'");
        TABLE_FIXES.put("t_scan_precheck_feedback",
            "CREATE TABLE IF NOT EXISTS `t_scan_precheck_feedback` ("
            + "`id` BIGINT NOT NULL AUTO_INCREMENT,"
            + "`tenant_id` BIGINT NOT NULL,"
            + "`scan_record_id` VARCHAR(64) DEFAULT NULL,"
            + "`order_no` VARCHAR(100) DEFAULT NULL,"
            + "`precheck_result` VARCHAR(32) DEFAULT NULL,"
            + "`user_action` VARCHAR(32) DEFAULT NULL,"
            + "`feedback_text` VARCHAR(500) DEFAULT NULL,"
            + "`created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,"
            + "PRIMARY KEY (`id`),"
            + "KEY `idx_spf_tenant_order` (`tenant_id`, `order_no`)"
            + ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='扫码预检反馈表'");
        TABLE_FIXES.put("t_order_risk_tracking",
            "CREATE TABLE IF NOT EXISTS `t_order_risk_tracking` ("
            + "`id` BIGINT NOT NULL AUTO_INCREMENT,"
            + "`tenant_id` BIGINT NOT NULL,"
            + "`order_no` VARCHAR(100) DEFAULT NULL,"
            + "`risk_type` VARCHAR(64) DEFAULT NULL,"
            + "`risk_level` VARCHAR(20) DEFAULT 'MEDIUM',"
            + "`description` TEXT DEFAULT NULL,"
            + "`status` VARCHAR(32) DEFAULT 'OPEN',"
            + "`assigned_to` VARCHAR(64) DEFAULT NULL,"
            + "`resolved_by` VARCHAR(64) DEFAULT NULL,"
            + "`resolution` TEXT DEFAULT NULL,"
            + "`resolved_at` DATETIME DEFAULT NULL,"
            + "`created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,"
            + "`updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,"
            + "PRIMARY KEY (`id`),"
            + "KEY `idx_ort_tenant_status` (`tenant_id`, `status`),"
            + "KEY `idx_ort_tenant_order` (`tenant_id`, `order_no`)"
            + ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='订单风险追踪表'");
        TABLE_FIXES.put("t_order_decision_snapshot",
            "CREATE TABLE IF NOT EXISTS `t_order_decision_snapshot` ("
            + "`id` BIGINT NOT NULL AUTO_INCREMENT,"
            + "`tenant_id` BIGINT NOT NULL,"
            + "`order_no` VARCHAR(100) NOT NULL,"
            + "`decision_type` VARCHAR(64) DEFAULT NULL,"
            + "`ai_suggestion` TEXT DEFAULT NULL,"
            + "`user_choice` VARCHAR(256) DEFAULT NULL,"
            + "`context_json` TEXT DEFAULT NULL,"
            + "`created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,"
            + "PRIMARY KEY (`id`),"
            + "KEY `idx_ods_tenant_order` (`tenant_id`, `order_no`)"
            + ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='订单决策快照表'");
        TABLE_FIXES.put("t_order_fulfillment_outcome",
            "CREATE TABLE IF NOT EXISTS `t_order_fulfillment_outcome` ("
            + "`id` BIGINT NOT NULL AUTO_INCREMENT,"
            + "`tenant_id` BIGINT NOT NULL,"
            + "`order_no` VARCHAR(100) NOT NULL,"
            + "`delivery_delay_days` INT DEFAULT NULL,"
            + "`cost_variance_pct` DOUBLE DEFAULT NULL,"
            + "`quality_pass_rate` DOUBLE DEFAULT NULL,"
            + "`outcome_json` TEXT DEFAULT NULL,"
            + "`created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,"
            + "PRIMARY KEY (`id`),"
            + "KEY `idx_ofo_tenant_order` (`tenant_id`, `order_no`)"
            + ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='订单履约结果表'");
        TABLE_FIXES.put("t_order_learning_outcome",
            "CREATE TABLE IF NOT EXISTS `t_order_learning_outcome` ("
            + "`id` BIGINT NOT NULL AUTO_INCREMENT,"
            + "`tenant_id` BIGINT NOT NULL,"
            + "`order_no` VARCHAR(100) DEFAULT NULL,"
            + "`learning_type` VARCHAR(64) DEFAULT NULL,"
            + "`insight` TEXT DEFAULT NULL,"
            + "`confidence` DOUBLE DEFAULT 0,"
            + "`adopted` TINYINT(1) DEFAULT 0,"
            + "`created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,"
            + "PRIMARY KEY (`id`),"
            + "KEY `idx_olo_tenant_order` (`tenant_id`, `order_no`)"
            + ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='订单学习结果表'");
        TABLE_FIXES.put("t_high_risk_audit_log",
            "CREATE TABLE IF NOT EXISTS `t_high_risk_audit_log` ("
            + "`id` BIGINT NOT NULL AUTO_INCREMENT,"
            + "`tenant_id` BIGINT NOT NULL,"
            + "`operation_type` VARCHAR(64) DEFAULT NULL,"
            + "`target_id` VARCHAR(100) DEFAULT NULL,"
            + "`operator_id` VARCHAR(64) DEFAULT NULL,"
            + "`risk_level` VARCHAR(20) DEFAULT 'HIGH',"
            + "`detail_json` TEXT DEFAULT NULL,"
            + "`approved` TINYINT(1) DEFAULT NULL,"
            + "`approver_id` VARCHAR(64) DEFAULT NULL,"
            + "`created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,"
            + "PRIMARY KEY (`id`),"
            + "KEY `idx_hral_tenant_time` (`tenant_id`, `created_at`)"
            + ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='高风险操作审计日志'");
    }
}