SET @dbname = DATABASE();

SET @c1 = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA=@dbname AND TABLE_NAME='t_workflow_definition');
SET @s1 = IF(@c1=0, 'CREATE TABLE t_workflow_definition (id VARCHAR(64) PRIMARY KEY, tenant_id BIGINT DEFAULT 0, name VARCHAR(255) NOT NULL, description TEXT, dag_json MEDIUMTEXT NOT NULL, version INT DEFAULT 1, enabled INT DEFAULT 1, delete_flag INT DEFAULT 0, created_by VARCHAR(64), created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX idx_wd_tenant(tenant_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4', 'SELECT 1');
PREPARE stmt1 FROM @s1; EXECUTE stmt1; DEALLOCATE PREPARE stmt1;

SET @c2 = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA=@dbname AND TABLE_NAME='t_workflow_execution');
SET @s2 = IF(@c2=0, 'CREATE TABLE t_workflow_execution (id VARCHAR(36) PRIMARY KEY, tenant_id BIGINT DEFAULT 0, user_id VARCHAR(64), workflow_id VARCHAR(64) NOT NULL, status VARCHAR(20) DEFAULT ''pending'', current_node_id VARCHAR(64), context_json MEDIUMTEXT, result_json MEDIUMTEXT, error_message TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX idx_we_tenant_user(tenant_id, user_id), INDEX idx_we_status(status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4', 'SELECT 1');
PREPARE stmt2 FROM @s2; EXECUTE stmt2; DEALLOCATE PREPARE stmt2;
