CREATE TABLE IF NOT EXISTS t_cutting_bom (
    id                      VARCHAR(36)   NOT NULL PRIMARY KEY,
    cutting_task_id         VARCHAR(36)   NOT NULL,
    production_order_no     VARCHAR(80),
    style_no                VARCHAR(50),
    material_code           VARCHAR(50),
    material_name           VARCHAR(100),
    material_type           VARCHAR(20)   DEFAULT 'accessory',
    fabric_composition      VARCHAR(100),
    fabric_weight           VARCHAR(50),
    color                   VARCHAR(100),
    specification           VARCHAR(100),
    unit                    VARCHAR(20),
    usage_amount            DECIMAL(10,4) DEFAULT 0,
    loss_rate               DECIMAL(5,2)  DEFAULT 0,
    unit_price              DECIMAL(10,2) DEFAULT 0.00,
    total_price             DECIMAL(10,2) DEFAULT 0.00,
    supplier_id             VARCHAR(50),
    supplier_name           VARCHAR(100),
    supplier_contact_person VARCHAR(50),
    supplier_contact_phone  VARCHAR(20),
    material_id             VARCHAR(36),
    image_urls              TEXT,
    remark                  VARCHAR(500),
    create_time             DATETIME,
    update_time             DATETIME,
    delete_flag             INT           DEFAULT 0,
    tenant_id               BIGINT,
    INDEX idx_cutting_bom_task_id (cutting_task_id),
    INDEX idx_cutting_bom_style_no (style_no),
    INDEX idx_cutting_bom_material_code (material_code),
    INDEX idx_cutting_bom_tenant_id (tenant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
