CREATE TABLE IF NOT EXISTS t_order_learning_outcome (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    order_id VARCHAR(64),
    order_no VARCHAR(64),
    decision_snapshot_id BIGINT,
    actual_factory_id VARCHAR(64),
    actual_factory_name VARCHAR(128),
    planned_finish_date DATETIME,
    actual_finish_date DATETIME,
    delay_days INT DEFAULT 0,
    estimated_unit_cost DECIMAL(12,4),
    actual_unit_cost DECIMAL(12,4),
    estimated_total_cost DECIMAL(12,4),
    actual_total_cost DECIMAL(12,4),
    actual_scatter_extra_cost DECIMAL(12,4),
    cost_deviation_rate DECIMAL(12,4),
    replenishment_count INT DEFAULT 0,
    rework_count INT DEFAULT 0,
    outcome_score DECIMAL(8,2),
    outcome_summary VARCHAR(500),
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_olo_tenant_order (tenant_id, order_id),
    INDEX idx_olo_tenant (tenant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
