-- 工厂发货单表：外发工厂分批发货 → 我方收货 → 质检入库
CREATE TABLE IF NOT EXISTS `t_factory_shipment` (
    `id` VARCHAR(36) NOT NULL,
    `shipment_no` VARCHAR(50) NOT NULL COMMENT '发货单号 FS+yyyyMMddHHmmss+3位随机',
    `order_id` VARCHAR(36) NOT NULL,
    `order_no` VARCHAR(50) DEFAULT NULL,
    `style_no` VARCHAR(50) DEFAULT NULL,
    `style_name` VARCHAR(200) DEFAULT NULL,
    `factory_id` VARCHAR(36) DEFAULT NULL,
    `factory_name` VARCHAR(100) DEFAULT NULL,
    `ship_quantity` INT NOT NULL DEFAULT 0 COMMENT '本次发货数量',
    `ship_time` DATETIME DEFAULT NULL COMMENT '发货时间',
    `shipped_by` VARCHAR(36) DEFAULT NULL,
    `shipped_by_name` VARCHAR(50) DEFAULT NULL,
    `tracking_no` VARCHAR(100) DEFAULT NULL COMMENT '物流单号',
    `express_company` VARCHAR(100) DEFAULT NULL COMMENT '快递/物流公司',
    `receive_status` VARCHAR(20) NOT NULL DEFAULT 'pending' COMMENT 'pending/received',
    `receive_time` DATETIME DEFAULT NULL,
    `received_by` VARCHAR(36) DEFAULT NULL,
    `received_by_name` VARCHAR(50) DEFAULT NULL,
    `remark` VARCHAR(500) DEFAULT NULL,
    `tenant_id` BIGINT DEFAULT NULL,
    `creator_id` VARCHAR(36) DEFAULT NULL,
    `creator_name` VARCHAR(50) DEFAULT NULL,
    `create_time` DATETIME DEFAULT NULL,
    `update_time` DATETIME DEFAULT NULL,
    `delete_flag` INT NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    INDEX `idx_fs_order_id` (`order_id`),
    INDEX `idx_fs_factory_id` (`factory_id`),
    INDEX `idx_fs_tenant_status` (`tenant_id`, `receive_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
