-- 为 t_material_picking 添加审核/财务字段
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_material_picking' AND COLUMN_NAME='purchase_id')=0,
  'ALTER TABLE `t_material_picking` ADD COLUMN `purchase_id` VARCHAR(64) DEFAULT NULL COMMENT ''关联采购单ID''',
  'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_material_picking' AND COLUMN_NAME='audit_status')=0,
  'ALTER TABLE `t_material_picking` ADD COLUMN `audit_status` VARCHAR(32) DEFAULT NULL COMMENT ''审核状态''',
  'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_material_picking' AND COLUMN_NAME='auditor_id')=0,
  'ALTER TABLE `t_material_picking` ADD COLUMN `auditor_id` VARCHAR(64) DEFAULT NULL COMMENT ''审核人ID''',
  'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_material_picking' AND COLUMN_NAME='auditor_name')=0,
  'ALTER TABLE `t_material_picking` ADD COLUMN `auditor_name` VARCHAR(128) DEFAULT NULL COMMENT ''审核人姓名''',
  'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_material_picking' AND COLUMN_NAME='audit_time')=0,
  'ALTER TABLE `t_material_picking` ADD COLUMN `audit_time` DATETIME DEFAULT NULL COMMENT ''审核时间''',
  'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_material_picking' AND COLUMN_NAME='audit_remark')=0,
  'ALTER TABLE `t_material_picking` ADD COLUMN `audit_remark` VARCHAR(500) DEFAULT NULL COMMENT ''审核备注''',
  'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_material_picking' AND COLUMN_NAME='finance_status')=0,
  'ALTER TABLE `t_material_picking` ADD COLUMN `finance_status` VARCHAR(32) DEFAULT NULL COMMENT ''财务状态''',
  'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_material_picking' AND COLUMN_NAME='finance_remark')=0,
  'ALTER TABLE `t_material_picking` ADD COLUMN `finance_remark` VARCHAR(500) DEFAULT NULL COMMENT ''财务备注''',
  'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- 为 t_material_picking_item 添加缺失字段
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_material_picking_item' AND COLUMN_NAME='specification')=0,
  'ALTER TABLE `t_material_picking_item` ADD COLUMN `specification` VARCHAR(200) DEFAULT NULL COMMENT ''规格''',
  'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_material_picking_item' AND COLUMN_NAME='unit_price')=0,
  'ALTER TABLE `t_material_picking_item` ADD COLUMN `unit_price` DECIMAL(12,2) DEFAULT NULL COMMENT ''单价''',
  'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_material_picking_item' AND COLUMN_NAME='supplier_name')=0,
  'ALTER TABLE `t_material_picking_item` ADD COLUMN `supplier_name` VARCHAR(200) DEFAULT NULL COMMENT ''供应商名称''',
  'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_material_picking_item' AND COLUMN_NAME='warehouse_location')=0,
  'ALTER TABLE `t_material_picking_item` ADD COLUMN `warehouse_location` VARCHAR(200) DEFAULT NULL COMMENT ''仓库位置''',
  'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_material_picking_item' AND COLUMN_NAME='material_type')=0,
  'ALTER TABLE `t_material_picking_item` ADD COLUMN `material_type` VARCHAR(50) DEFAULT NULL COMMENT ''物料类型''',
  'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
