-- V20260422002: 全面补齐 Entity 声明但数据库缺失的列（DbColumnRepairRunner 双重保障）
-- 使用 SET @s + PREPARE/EXECUTE 实现幂等，避免 DELIMITER 语法问题

-- ── t_style_info 遗漏列（导致 /api/style/info/list 500）──
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_style_info' AND COLUMN_NAME='skc')=0,
  'ALTER TABLE `t_style_info` ADD COLUMN `skc` VARCHAR(100) DEFAULT NULL COMMENT ''SKC统编号''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_style_info' AND COLUMN_NAME='pushed_to_order')=0,
  'ALTER TABLE `t_style_info` ADD COLUMN `pushed_to_order` INT DEFAULT NULL COMMENT ''是否已推送到下单管理''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_style_info' AND COLUMN_NAME='pushed_to_order_time')=0,
  'ALTER TABLE `t_style_info` ADD COLUMN `pushed_to_order_time` DATETIME DEFAULT NULL COMMENT ''推送时间''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_style_info' AND COLUMN_NAME='customer')=0,
  'ALTER TABLE `t_style_info` ADD COLUMN `customer` VARCHAR(100) DEFAULT NULL COMMENT ''客户''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_style_info' AND COLUMN_NAME='order_no')=0,
  'ALTER TABLE `t_style_info` ADD COLUMN `order_no` VARCHAR(100) DEFAULT NULL COMMENT ''关联订单号''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_style_info' AND COLUMN_NAME='sample_status')=0,
  'ALTER TABLE `t_style_info` ADD COLUMN `sample_status` VARCHAR(20) DEFAULT NULL COMMENT ''样衣状态''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_style_info' AND COLUMN_NAME='sample_progress')=0,
  'ALTER TABLE `t_style_info` ADD COLUMN `sample_progress` INT DEFAULT NULL COMMENT ''样衣进度''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_style_info' AND COLUMN_NAME='sample_completed_time')=0,
  'ALTER TABLE `t_style_info` ADD COLUMN `sample_completed_time` DATETIME DEFAULT NULL COMMENT ''样衣完成时间''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- ── t_product_outstock 审批列 ──
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_product_outstock' AND COLUMN_NAME='approval_status')=0,
  'ALTER TABLE `t_product_outstock` ADD COLUMN `approval_status` VARCHAR(20) DEFAULT NULL COMMENT ''审批状态''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_product_outstock' AND COLUMN_NAME='approve_by')=0,
  'ALTER TABLE `t_product_outstock` ADD COLUMN `approve_by` VARCHAR(64) DEFAULT NULL COMMENT ''审批人ID''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_product_outstock' AND COLUMN_NAME='approve_by_name')=0,
  'ALTER TABLE `t_product_outstock` ADD COLUMN `approve_by_name` VARCHAR(100) DEFAULT NULL COMMENT ''审批人姓名''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_product_outstock' AND COLUMN_NAME='approve_time')=0,
  'ALTER TABLE `t_product_outstock` ADD COLUMN `approve_time` DATETIME DEFAULT NULL COMMENT ''审批时间''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- ── t_secondary_process 审批列 ──
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_secondary_process' AND COLUMN_NAME='approval_status')=0,
  'ALTER TABLE `t_secondary_process` ADD COLUMN `approval_status` VARCHAR(20) DEFAULT NULL COMMENT ''审批状态''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_secondary_process' AND COLUMN_NAME='approved_by_id')=0,
  'ALTER TABLE `t_secondary_process` ADD COLUMN `approved_by_id` VARCHAR(64) DEFAULT NULL COMMENT ''审批人ID''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_secondary_process' AND COLUMN_NAME='approved_by_name')=0,
  'ALTER TABLE `t_secondary_process` ADD COLUMN `approved_by_name` VARCHAR(128) DEFAULT NULL COMMENT ''审批人姓名''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_secondary_process' AND COLUMN_NAME='approved_time')=0,
  'ALTER TABLE `t_secondary_process` ADD COLUMN `approved_time` DATETIME DEFAULT NULL COMMENT ''审批时间''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- ── t_pattern_production 审核列 ──
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_pattern_production' AND COLUMN_NAME='review_status')=0,
  'ALTER TABLE `t_pattern_production` ADD COLUMN `review_status` VARCHAR(20) DEFAULT NULL COMMENT ''审核状态''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_pattern_production' AND COLUMN_NAME='review_result')=0,
  'ALTER TABLE `t_pattern_production` ADD COLUMN `review_result` VARCHAR(20) DEFAULT NULL COMMENT ''审核结论''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_pattern_production' AND COLUMN_NAME='review_remark')=0,
  'ALTER TABLE `t_pattern_production` ADD COLUMN `review_remark` VARCHAR(500) DEFAULT NULL COMMENT ''审核备注''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_pattern_production' AND COLUMN_NAME='review_by')=0,
  'ALTER TABLE `t_pattern_production` ADD COLUMN `review_by` VARCHAR(100) DEFAULT NULL COMMENT ''审核人姓名''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_pattern_production' AND COLUMN_NAME='review_by_id')=0,
  'ALTER TABLE `t_pattern_production` ADD COLUMN `review_by_id` VARCHAR(64) DEFAULT NULL COMMENT ''审核人ID''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_pattern_production' AND COLUMN_NAME='review_time')=0,
  'ALTER TABLE `t_pattern_production` ADD COLUMN `review_time` DATETIME DEFAULT NULL COMMENT ''审核时间''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_pattern_production' AND COLUMN_NAME='has_secondary_process')=0,
  'ALTER TABLE `t_pattern_production` ADD COLUMN `has_secondary_process` TINYINT(1) NOT NULL DEFAULT 1 COMMENT ''是否有二次工艺''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- ── t_user 审批/注册列 ──
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_user' AND COLUMN_NAME='approval_status')=0,
  'ALTER TABLE `t_user` ADD COLUMN `approval_status` VARCHAR(20) DEFAULT NULL COMMENT ''审批状态''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_user' AND COLUMN_NAME='approval_time')=0,
  'ALTER TABLE `t_user` ADD COLUMN `approval_time` DATETIME DEFAULT NULL COMMENT ''审批时间''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_user' AND COLUMN_NAME='approval_remark')=0,
  'ALTER TABLE `t_user` ADD COLUMN `approval_remark` VARCHAR(500) DEFAULT NULL COMMENT ''审批备注''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_user' AND COLUMN_NAME='registration_status')=0,
  'ALTER TABLE `t_user` ADD COLUMN `registration_status` VARCHAR(20) DEFAULT NULL COMMENT ''注册状态''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_user' AND COLUMN_NAME='reject_reason')=0,
  'ALTER TABLE `t_user` ADD COLUMN `reject_reason` VARCHAR(500) DEFAULT NULL COMMENT ''拒绝原因''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_user' AND COLUMN_NAME='phone')=0,
  'ALTER TABLE `t_user` ADD COLUMN `phone` VARCHAR(20) DEFAULT NULL COMMENT ''手机号''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_user' AND COLUMN_NAME='email')=0,
  'ALTER TABLE `t_user` ADD COLUMN `email` VARCHAR(100) DEFAULT NULL COMMENT ''邮箱''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_user' AND COLUMN_NAME='openid')=0,
  'ALTER TABLE `t_user` ADD COLUMN `openid` VARCHAR(100) DEFAULT NULL COMMENT ''微信openid''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- ── t_production_order 遗漏列（导致 /api/production/order/list 500）──
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_production_order' AND COLUMN_NAME='delete_flag')=0,
  'ALTER TABLE `t_production_order` ADD COLUMN `delete_flag` INT NOT NULL DEFAULT 0 COMMENT ''删除标志''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_production_order' AND COLUMN_NAME='completed_quantity')=0,
  'ALTER TABLE `t_production_order` ADD COLUMN `completed_quantity` INT DEFAULT NULL COMMENT ''完成数量''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_production_order' AND COLUMN_NAME='tenant_id')=0,
  'ALTER TABLE `t_production_order` ADD COLUMN `tenant_id` BIGINT DEFAULT NULL COMMENT ''租户ID''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- ── t_material_picking 遗漏列 ──
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_material_picking' AND COLUMN_NAME='pickup_type')=0,
  'ALTER TABLE `t_material_picking` ADD COLUMN `pickup_type` VARCHAR(20) DEFAULT NULL COMMENT ''领取类型''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_material_picking' AND COLUMN_NAME='usage_type')=0,
  'ALTER TABLE `t_material_picking` ADD COLUMN `usage_type` VARCHAR(30) DEFAULT NULL COMMENT ''用途类型''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_material_picking' AND COLUMN_NAME='pick_time')=0,
  'ALTER TABLE `t_material_picking` ADD COLUMN `pick_time` DATETIME DEFAULT NULL COMMENT ''领取时间''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_material_picking' AND COLUMN_NAME='delete_flag')=0,
  'ALTER TABLE `t_material_picking` ADD COLUMN `delete_flag` INT NOT NULL DEFAULT 0 COMMENT ''删除标记''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
