-- V20260328: 幂等 ALTER TABLE 添加 difficulty 列
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_style_process' AND COLUMN_NAME='difficulty')=0,
    'ALTER TABLE `t_style_process` ADD COLUMN `difficulty` VARCHAR(10) DEFAULT NULL AFTER `machine_type`',
    'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
