CREATE TABLE IF NOT EXISTS `t_material_quality_issue` (
  `id` VARCHAR(64) NOT NULL,
  `issue_no` VARCHAR(64) NOT NULL,
  `purchase_id` VARCHAR(64) NOT NULL,
  `purchase_no` VARCHAR(64) DEFAULT NULL,
  `order_id` VARCHAR(64) DEFAULT NULL,
  `order_no` VARCHAR(64) DEFAULT NULL,
  `style_id` VARCHAR(64) DEFAULT NULL,
  `style_no` VARCHAR(64) DEFAULT NULL,
  `supplier_id` VARCHAR(64) DEFAULT NULL,
  `supplier_name` VARCHAR(128) DEFAULT NULL,
  `material_id` VARCHAR(64) DEFAULT NULL,
  `material_code` VARCHAR(64) DEFAULT NULL,
  `material_name` VARCHAR(128) DEFAULT NULL,
  `material_type` VARCHAR(64) DEFAULT NULL,
  `issue_quantity` INT DEFAULT 0,
  `issue_type` VARCHAR(32) DEFAULT NULL,
  `severity` VARCHAR(32) DEFAULT NULL,
  `disposition` VARCHAR(32) DEFAULT NULL,
  `status` VARCHAR(32) DEFAULT NULL,
  `evidence_image_urls` TEXT,
  `remark` VARCHAR(500) DEFAULT NULL,
  `resolution_remark` VARCHAR(500) DEFAULT NULL,
  `related_purchase_id` VARCHAR(64) DEFAULT NULL,
  `related_purchase_no` VARCHAR(64) DEFAULT NULL,
  `deduction_amount` DECIMAL(18,2) DEFAULT NULL,
  `reporter_id` VARCHAR(64) DEFAULT NULL,
  `reporter_name` VARCHAR(64) DEFAULT NULL,
  `resolver_id` VARCHAR(64) DEFAULT NULL,
  `resolver_name` VARCHAR(64) DEFAULT NULL,
  `resolved_time` DATETIME DEFAULT NULL,
  `tenant_id` BIGINT DEFAULT NULL,
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `delete_flag` TINYINT(1) DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_material_quality_issue_no` (`issue_no`),
  KEY `idx_material_quality_issue_purchase` (`purchase_id`),
  KEY `idx_material_quality_issue_tenant_status` (`tenant_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
