CREATE TABLE IF NOT EXISTS t_inventory_check (
    id              VARCHAR(64)  NOT NULL PRIMARY KEY,
    check_no        VARCHAR(64)  NOT NULL,
    check_type      VARCHAR(32)  NOT NULL,
    status          VARCHAR(32)  NOT NULL DEFAULT 'draft',
    check_date      DATE         NOT NULL,
    warehouse_location VARCHAR(128),
    total_items     INT          NOT NULL DEFAULT 0,
    diff_items      INT          NOT NULL DEFAULT 0,
    total_book_qty  INT          NOT NULL DEFAULT 0,
    total_actual_qty INT         NOT NULL DEFAULT 0,
    total_diff_qty  INT          NOT NULL DEFAULT 0,
    total_diff_amount DECIMAL(14,2) NOT NULL DEFAULT 0,
    remark          TEXT,
    confirmed_by    VARCHAR(64),
    confirmed_name  VARCHAR(128),
    confirmed_time  DATETIME,
    created_by_id   VARCHAR(64),
    created_by_name VARCHAR(128),
    tenant_id       BIGINT       NOT NULL,
    delete_flag     INT          NOT NULL DEFAULT 0,
    create_time     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_check_no_tenant (check_no, tenant_id),
    KEY idx_tenant_status (tenant_id, status),
    KEY idx_check_date (check_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS t_inventory_check_item (
    id              VARCHAR(64)  NOT NULL PRIMARY KEY,
    check_id        VARCHAR(64)  NOT NULL,
    stock_id        VARCHAR(64),
    material_code   VARCHAR(128),
    material_name   VARCHAR(256),
    sku_code        VARCHAR(128),
    color           VARCHAR(64),
    size            VARCHAR(64),
    specifications  VARCHAR(512),
    unit            VARCHAR(32),
    unit_price      DECIMAL(14,4),
    book_quantity   INT          NOT NULL DEFAULT 0,
    actual_quantity  INT,
    diff_quantity   INT,
    diff_amount     DECIMAL(14,2),
    diff_type       VARCHAR(32),
    check_status    VARCHAR(32)  NOT NULL DEFAULT 'pending',
    remark          VARCHAR(512),
    tenant_id       BIGINT       NOT NULL,
    delete_flag     INT          NOT NULL DEFAULT 0,
    create_time     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_check_id (check_id),
    KEY idx_tenant (tenant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;