SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_style_info' AND COLUMN_NAME='sample_start_time')=0,
  'ALTER TABLE `t_style_info` ADD COLUMN `sample_start_time` DATETIME DEFAULT NULL COMMENT ''样衣生产开始时间''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
