CREATE TABLE IF NOT EXISTS t_inventory_check (
    id              VARCHAR(64)  NOT NULL PRIMARY KEY,
    check_no        VARCHAR(64)  NOT NULL COMMENT '盘点单号',
    check_type      VARCHAR(32)  NOT NULL COMMENT 'MATERIAL=物料/FINISHED=成品',
    status          VARCHAR(32)  NOT NULL DEFAULT 'draft' COMMENT 'draft/checked/confirmed/cancelled',
    check_date      DATE         NOT NULL COMMENT '盘点日期',
    warehouse_location VARCHAR(128) COMMENT '仓库位置',
    total_items     INT          NOT NULL DEFAULT 0 COMMENT '盘点项总数',
    diff_items      INT          NOT NULL DEFAULT 0 COMMENT '差异数',
    total_book_qty  INT          NOT NULL DEFAULT 0 COMMENT '账面总数',
    total_actual_qty INT         NOT NULL DEFAULT 0 COMMENT '实盘总数',
    total_diff_qty  INT          NOT NULL DEFAULT 0 COMMENT '差异数量',
    total_diff_amount DECIMAL(14,2) NOT NULL DEFAULT 0 COMMENT '差异金额',
    remark          TEXT         COMMENT '备注',
    confirmed_by    VARCHAR(64)  COMMENT '确认人ID',
    confirmed_name  VARCHAR(128) COMMENT '确认人姓名',
    confirmed_time  DATETIME     COMMENT '确认时间',
    created_by_id   VARCHAR(64)  COMMENT '创建人ID',
    created_by_name VARCHAR(128) COMMENT '创建人姓名',
    tenant_id       BIGINT       NOT NULL COMMENT '租户ID',
    delete_flag     INT          NOT NULL DEFAULT 0,
    create_time     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_check_no_tenant (check_no, tenant_id),
    KEY idx_tenant_status (tenant_id, status),
    KEY idx_check_date (check_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='库存盘点单';

CREATE TABLE IF NOT EXISTS t_inventory_check_item (
    id              VARCHAR(64)  NOT NULL PRIMARY KEY,
    check_id        VARCHAR(64)  NOT NULL COMMENT '盘点单ID',
    stock_id        VARCHAR(64)  COMMENT '库存记录ID',
    material_code   VARCHAR(128) COMMENT '物料编码',
    material_name   VARCHAR(256) COMMENT '物料名称',
    sku_code        VARCHAR(128) COMMENT 'SKU编码',
    color           VARCHAR(64)  COMMENT '颜色',
    size            VARCHAR(64)  COMMENT '尺码',
    specifications  VARCHAR(512) COMMENT '规格',
    unit            VARCHAR(32)  COMMENT '单位',
    unit_price      DECIMAL(14,4) COMMENT '单价',
    book_quantity   INT          NOT NULL DEFAULT 0 COMMENT '账面数量',
    actual_quantity  INT          COMMENT '实盘数量',
    diff_quantity   INT          COMMENT '差异数量(实盘-账面)',
    diff_amount     DECIMAL(14,2) COMMENT '差异金额',
    diff_type       VARCHAR(32)  COMMENT 'PROFIT=盘盈/LOSS=盘亏/EQUAL=持平',
    check_status    VARCHAR(32)  NOT NULL DEFAULT 'pending' COMMENT 'pending/checked',
    remark          VARCHAR(512) COMMENT '备注',
    tenant_id       BIGINT       NOT NULL COMMENT '租户ID',
    delete_flag     INT          NOT NULL DEFAULT 0,
    create_time     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_check_id (check_id),
    KEY idx_tenant (tenant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='库存盘点明细';
