SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_deduction_item' AND COLUMN_NAME='source_type')=0,'ALTER TABLE t_deduction_item ADD COLUMN source_type VARCHAR(64) DEFAULT NULL','SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_deduction_item' AND COLUMN_NAME='source_id')=0,'ALTER TABLE t_deduction_item ADD COLUMN source_id VARCHAR(64) DEFAULT NULL','SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
