-- =====================================================================
-- 全库系统性修复：size/color 短列批量扩宽（D-110 拼接字段列宽风险根治）
--
-- 现象：POST /api/production/order 500 "Data truncation: Data too long for column 'size'"
-- 根因：下单主表 size 存多码拼接串（6 个国标码 join(',') = 72 字符），
--       t_production_order.size 仅 VARCHAR(50)。此前 t_style_info(V202708172000)、
--       t_style_bom(V202708201800) 已两次同根因复发，本次全库扫描 INFORMATION_SCHEMA
--       后对 50+ 列一次性扩宽，彻底根治"打地鼠"式修复。
--
-- 策略：
--   1) 业务主表（订单/裁剪/采购/出库等，size/color 存多值拼接串）→ VARCHAR(500)
--   2) 单值表（扫码/SKU/退货等，存单个码数/颜色）→ VARCHAR(200) 防御性扩宽
--      （国标码 "XS(155/72A)" 已 11 字符，t_stock_change_log.size 原仅 16，极危）
--   3) orphan_backup 备份表不动
--
-- 幂等：仅当当前 CHARACTER_MAXIMUM_LENGTH < 目标长度时执行 MODIFY，可重复执行。
-- 注意：SET @s 内 COMMENT 使用双单引号转义（Flyway 静默失败陷阱）。
-- =====================================================================

-- ============ 一、业务主表（拼接串语义）→ VARCHAR(500) ============

-- t_production_order（下单主表：size=多码 join(',')，color=多色拼接）
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_production_order' AND COLUMN_NAME='size' AND CHARACTER_MAXIMUM_LENGTH < 500) > 0, 'ALTER TABLE `t_production_order` MODIFY COLUMN `size` VARCHAR(500) NULL COMMENT ''尺码（多码逗号拼接）''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_production_order' AND COLUMN_NAME='color' AND CHARACTER_MAXIMUM_LENGTH < 500) > 0, 'ALTER TABLE `t_production_order` MODIFY COLUMN `color` VARCHAR(500) NULL COMMENT ''颜色（多色逗号拼接）''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- t_production_process_tracking（工序进度跟踪）
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_production_process_tracking' AND COLUMN_NAME='size' AND CHARACTER_MAXIMUM_LENGTH < 500) > 0, 'ALTER TABLE `t_production_process_tracking` MODIFY COLUMN `size` VARCHAR(500) NULL COMMENT ''尺码''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_production_process_tracking' AND COLUMN_NAME='color' AND CHARACTER_MAXIMUM_LENGTH < 500) > 0, 'ALTER TABLE `t_production_process_tracking` MODIFY COLUMN `color` VARCHAR(500) NULL COMMENT ''颜色''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- t_cutting_bundle（裁剪分扎）
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_cutting_bundle' AND COLUMN_NAME='size' AND CHARACTER_MAXIMUM_LENGTH < 500) > 0, 'ALTER TABLE `t_cutting_bundle` MODIFY COLUMN `size` VARCHAR(500) NULL COMMENT ''码数''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_cutting_bundle' AND COLUMN_NAME='color' AND CHARACTER_MAXIMUM_LENGTH < 500) > 0, 'ALTER TABLE `t_cutting_bundle` MODIFY COLUMN `color` VARCHAR(500) NULL COMMENT ''颜色''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- t_cutting_task（裁剪任务）
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_cutting_task' AND COLUMN_NAME='size' AND CHARACTER_MAXIMUM_LENGTH < 500) > 0, 'ALTER TABLE `t_cutting_task` MODIFY COLUMN `size` VARCHAR(500) NULL COMMENT ''码数''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_cutting_task' AND COLUMN_NAME='color' AND CHARACTER_MAXIMUM_LENGTH < 500) > 0, 'ALTER TABLE `t_cutting_task` MODIFY COLUMN `color` VARCHAR(500) NULL COMMENT ''颜色''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- t_cutting_bom（裁剪 BOM）
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_cutting_bom' AND COLUMN_NAME='size' AND CHARACTER_MAXIMUM_LENGTH < 500) > 0, 'ALTER TABLE `t_cutting_bom` MODIFY COLUMN `size` VARCHAR(500) NULL COMMENT ''尺码''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_cutting_bom' AND COLUMN_NAME='color' AND CHARACTER_MAXIMUM_LENGTH < 500) > 0, 'ALTER TABLE `t_cutting_bom` MODIFY COLUMN `color` VARCHAR(500) NULL COMMENT ''颜色''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- t_material_purchase（物料采购：size 存"6码：XS.../S..."拼接）
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_material_purchase' AND COLUMN_NAME='size' AND CHARACTER_MAXIMUM_LENGTH < 500) > 0, 'ALTER TABLE `t_material_purchase` MODIFY COLUMN `size` VARCHAR(500) NULL COMMENT ''尺码（从样衣同步）''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_material_purchase' AND COLUMN_NAME='color' AND CHARACTER_MAXIMUM_LENGTH < 500) > 0, 'ALTER TABLE `t_material_purchase` MODIFY COLUMN `color` VARCHAR(500) NULL COMMENT ''颜色（从样衣同步）''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- t_material_picking_item（领料明细）
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_material_picking_item' AND COLUMN_NAME='size' AND CHARACTER_MAXIMUM_LENGTH < 500) > 0, 'ALTER TABLE `t_material_picking_item` MODIFY COLUMN `size` VARCHAR(500) NULL COMMENT ''规格/尺码''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_material_picking_item' AND COLUMN_NAME='color' AND CHARACTER_MAXIMUM_LENGTH < 500) > 0, 'ALTER TABLE `t_material_picking_item` MODIFY COLUMN `color` VARCHAR(500) NULL COMMENT ''颜色''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- t_material_inbound（物料入库）
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_material_inbound' AND COLUMN_NAME='size' AND CHARACTER_MAXIMUM_LENGTH < 500) > 0, 'ALTER TABLE `t_material_inbound` MODIFY COLUMN `size` VARCHAR(500) NULL COMMENT ''规格/尺寸''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_material_inbound' AND COLUMN_NAME='color' AND CHARACTER_MAXIMUM_LENGTH < 500) > 0, 'ALTER TABLE `t_material_inbound` MODIFY COLUMN `color` VARCHAR(500) NULL COMMENT ''颜色''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- t_purchase_cart_item（采购车）
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_purchase_cart_item' AND COLUMN_NAME='color' AND CHARACTER_MAXIMUM_LENGTH < 500) > 0, 'ALTER TABLE `t_purchase_cart_item` MODIFY COLUMN `color` VARCHAR(500) NULL COMMENT ''颜色''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- t_product_outstock（成品出库）
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_product_outstock' AND COLUMN_NAME='size' AND CHARACTER_MAXIMUM_LENGTH < 500) > 0, 'ALTER TABLE `t_product_outstock` MODIFY COLUMN `size` VARCHAR(500) NULL COMMENT ''尺码''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_product_outstock' AND COLUMN_NAME='color' AND CHARACTER_MAXIMUM_LENGTH < 500) > 0, 'ALTER TABLE `t_product_outstock` MODIFY COLUMN `color` VARCHAR(500) NULL COMMENT ''颜色''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- t_pattern_production（样衣生产：多色多码任务）
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_pattern_production' AND COLUMN_NAME='size' AND CHARACTER_MAXIMUM_LENGTH < 500) > 0, 'ALTER TABLE `t_pattern_production` MODIFY COLUMN `size` VARCHAR(500) NULL COMMENT ''尺码''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_pattern_production' AND COLUMN_NAME='color' AND CHARACTER_MAXIMUM_LENGTH < 500) > 0, 'ALTER TABLE `t_pattern_production` MODIFY COLUMN `color` VARCHAR(500) NULL COMMENT ''颜色''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- t_style_info（款式：开发颜色多色拼接）
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_style_info' AND COLUMN_NAME='color' AND CHARACTER_MAXIMUM_LENGTH < 500) > 0, 'ALTER TABLE `t_style_info` MODIFY COLUMN `color` VARCHAR(500) NULL COMMENT ''颜色（开发多色拼接）''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- ============ 二、单值表（防御性）→ VARCHAR(200) ============

-- t_product_sku（SKU：原 VARCHAR(32) 偏紧）
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_product_sku' AND COLUMN_NAME='size' AND CHARACTER_MAXIMUM_LENGTH < 200) > 0, 'ALTER TABLE `t_product_sku` MODIFY COLUMN `size` VARCHAR(200) NOT NULL COMMENT ''尺码''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_product_sku' AND COLUMN_NAME='color' AND CHARACTER_MAXIMUM_LENGTH < 200) > 0, 'ALTER TABLE `t_product_sku` MODIFY COLUMN `color` VARCHAR(200) NOT NULL COMMENT ''颜色''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- t_scan_record（工序扫码）
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_scan_record' AND COLUMN_NAME='size' AND CHARACTER_MAXIMUM_LENGTH < 200) > 0, 'ALTER TABLE `t_scan_record` MODIFY COLUMN `size` VARCHAR(200) NULL COMMENT ''码数''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_scan_record' AND COLUMN_NAME='color' AND CHARACTER_MAXIMUM_LENGTH < 200) > 0, 'ALTER TABLE `t_scan_record` MODIFY COLUMN `color` VARCHAR(200) NULL COMMENT ''颜色''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- t_pattern_scan_record（样衣扫码）
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_pattern_scan_record' AND COLUMN_NAME='size' AND CHARACTER_MAXIMUM_LENGTH < 200) > 0, 'ALTER TABLE `t_pattern_scan_record` MODIFY COLUMN `size` VARCHAR(200) NULL COMMENT ''码数''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_pattern_scan_record' AND COLUMN_NAME='color' AND CHARACTER_MAXIMUM_LENGTH < 200) > 0, 'ALTER TABLE `t_pattern_scan_record` MODIFY COLUMN `color` VARCHAR(200) NULL COMMENT ''颜色''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- t_stock_change_log（库存变动日志：原 size VARCHAR(16) 极危，国标码 11 字符仅剩 5 余量）
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_stock_change_log' AND COLUMN_NAME='size' AND CHARACTER_MAXIMUM_LENGTH < 200) > 0, 'ALTER TABLE `t_stock_change_log` MODIFY COLUMN `size` VARCHAR(200) NULL COMMENT ''码数''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_stock_change_log' AND COLUMN_NAME='color' AND CHARACTER_MAXIMUM_LENGTH < 200) > 0, 'ALTER TABLE `t_stock_change_log` MODIFY COLUMN `color` VARCHAR(200) NULL COMMENT ''颜色''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- t_stock_transfer（库存转移：原 size VARCHAR(16) 极危）
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_stock_transfer' AND COLUMN_NAME='size' AND CHARACTER_MAXIMUM_LENGTH < 200) > 0, 'ALTER TABLE `t_stock_transfer` MODIFY COLUMN `size` VARCHAR(200) NULL COMMENT ''码数''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_stock_transfer' AND COLUMN_NAME='color' AND CHARACTER_MAXIMUM_LENGTH < 200) > 0, 'ALTER TABLE `t_stock_transfer` MODIFY COLUMN `color` VARCHAR(200) NULL COMMENT ''颜色''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- t_purchase_return_item（采购退货）
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_purchase_return_item' AND COLUMN_NAME='size' AND CHARACTER_MAXIMUM_LENGTH < 200) > 0, 'ALTER TABLE `t_purchase_return_item` MODIFY COLUMN `size` VARCHAR(200) NULL COMMENT ''码数''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_purchase_return_item' AND COLUMN_NAME='color' AND CHARACTER_MAXIMUM_LENGTH < 200) > 0, 'ALTER TABLE `t_purchase_return_item` MODIFY COLUMN `color` VARCHAR(200) NULL COMMENT ''颜色''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- t_sales_return_item（销售退货）
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_sales_return_item' AND COLUMN_NAME='size' AND CHARACTER_MAXIMUM_LENGTH < 200) > 0, 'ALTER TABLE `t_sales_return_item` MODIFY COLUMN `size` VARCHAR(200) NULL COMMENT ''码数''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_sales_return_item' AND COLUMN_NAME='color' AND CHARACTER_MAXIMUM_LENGTH < 200) > 0, 'ALTER TABLE `t_sales_return_item` MODIFY COLUMN `color` VARCHAR(200) NULL COMMENT ''颜色''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- t_factory_shipment_detail（外发出货明细，color 为 NOT NULL）
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_factory_shipment_detail' AND COLUMN_NAME='color' AND CHARACTER_MAXIMUM_LENGTH < 200) > 0, 'ALTER TABLE `t_factory_shipment_detail` MODIFY COLUMN `color` VARCHAR(200) NOT NULL COMMENT ''颜色''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- t_material_roll（色卡卷）
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_material_roll' AND COLUMN_NAME='color' AND CHARACTER_MAXIMUM_LENGTH < 200) > 0, 'ALTER TABLE `t_material_roll` MODIFY COLUMN `color` VARCHAR(200) NULL COMMENT ''颜色''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- t_inventory_check_item（盘点明细）
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_inventory_check_item' AND COLUMN_NAME='size' AND CHARACTER_MAXIMUM_LENGTH < 200) > 0, 'ALTER TABLE `t_inventory_check_item` MODIFY COLUMN `size` VARCHAR(200) NULL COMMENT ''码数''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_inventory_check_item' AND COLUMN_NAME='color' AND CHARACTER_MAXIMUM_LENGTH < 200) > 0, 'ALTER TABLE `t_inventory_check_item` MODIFY COLUMN `color` VARCHAR(200) NULL COMMENT ''颜色''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- t_material_stock（物料库存）
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_material_stock' AND COLUMN_NAME='size' AND CHARACTER_MAXIMUM_LENGTH < 200) > 0, 'ALTER TABLE `t_material_stock` MODIFY COLUMN `size` VARCHAR(200) NULL COMMENT ''码数''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_material_stock' AND COLUMN_NAME='color' AND CHARACTER_MAXIMUM_LENGTH < 200) > 0, 'ALTER TABLE `t_material_stock` MODIFY COLUMN `color` VARCHAR(200) NULL COMMENT ''颜色''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- t_payroll_settlement_item（工资结算明细）
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_payroll_settlement_item' AND COLUMN_NAME='size' AND CHARACTER_MAXIMUM_LENGTH < 200) > 0, 'ALTER TABLE `t_payroll_settlement_item` MODIFY COLUMN `size` VARCHAR(200) NULL COMMENT ''码数''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_payroll_settlement_item' AND COLUMN_NAME='color' AND CHARACTER_MAXIMUM_LENGTH < 200) > 0, 'ALTER TABLE `t_payroll_settlement_item` MODIFY COLUMN `color` VARCHAR(200) NULL COMMENT ''颜色''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- t_sample_stock（样衣库存）
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_sample_stock' AND COLUMN_NAME='size' AND CHARACTER_MAXIMUM_LENGTH < 200) > 0, 'ALTER TABLE `t_sample_stock` MODIFY COLUMN `size` VARCHAR(200) NULL COMMENT ''码数''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_sample_stock' AND COLUMN_NAME='color' AND CHARACTER_MAXIMUM_LENGTH < 200) > 0, 'ALTER TABLE `t_sample_stock` MODIFY COLUMN `color` VARCHAR(200) NULL COMMENT ''颜色''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- t_material_pickup_record（领料记录）
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_material_pickup_record' AND COLUMN_NAME='color' AND CHARACTER_MAXIMUM_LENGTH < 200) > 0, 'ALTER TABLE `t_material_pickup_record` MODIFY COLUMN `color` VARCHAR(200) NULL COMMENT ''颜色''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- t_style_size_price（码数单价，size 原 VARCHAR(20) 偏紧）
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_style_size_price' AND COLUMN_NAME='size' AND CHARACTER_MAXIMUM_LENGTH < 200) > 0, 'ALTER TABLE `t_style_size_price` MODIFY COLUMN `size` VARCHAR(200) NOT NULL COMMENT ''尺码''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- t_material_color_card_item（色卡明细）
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_material_color_card_item' AND COLUMN_NAME='color' AND CHARACTER_MAXIMUM_LENGTH < 200) > 0, 'ALTER TABLE `t_material_color_card_item` MODIFY COLUMN `color` VARCHAR(200) NULL COMMENT ''颜色''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- t_material_database（物料资料）
SET @s = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_material_database' AND COLUMN_NAME='color' AND CHARACTER_MAXIMUM_LENGTH < 200) > 0, 'ALTER TABLE `t_material_database` MODIFY COLUMN `color` VARCHAR(200) NULL COMMENT ''颜色''', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
