CREATE TABLE IF NOT EXISTS t_intelligence_feedback_reason (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    tenant_id BIGINT NOT NULL COMMENT '租户ID',
    prediction_id VARCHAR(64) DEFAULT NULL COMMENT '关联预测/建议ID',
    suggestion_type VARCHAR(64) DEFAULT NULL COMMENT '建议类型',
    accepted TINYINT(1) DEFAULT NULL COMMENT '是否接受建议',
    reason_code VARCHAR(64) DEFAULT NULL COMMENT '原因编码',
    reason_text VARCHAR(500) DEFAULT NULL COMMENT '原因说明',
    order_id VARCHAR(64) DEFAULT NULL COMMENT '订单ID',
    order_no VARCHAR(64) DEFAULT NULL COMMENT '订单号',
    stage_name VARCHAR(64) DEFAULT NULL COMMENT '阶段名',
    process_name VARCHAR(64) DEFAULT NULL COMMENT '工序名',
    operator_id VARCHAR(64) DEFAULT NULL COMMENT '操作人ID',
    operator_name VARCHAR(64) DEFAULT NULL COMMENT '操作人姓名',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    delete_flag INT DEFAULT 0,
    KEY idx_ifr_tenant_id (tenant_id),
    KEY idx_ifr_prediction_id (prediction_id),
    KEY idx_ifr_suggestion_type (suggestion_type),
    KEY idx_ifr_reason_code (reason_code)
) COMMENT='智能建议采纳与拒绝原因记录';

CREATE TABLE IF NOT EXISTS t_intelligence_pain_point (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    tenant_id BIGINT NOT NULL COMMENT '租户ID',
    pain_code VARCHAR(64) NOT NULL COMMENT '痛点编码',
    pain_name VARCHAR(128) NOT NULL COMMENT '痛点名称',
    pain_level VARCHAR(16) NOT NULL COMMENT '痛点级别',
    business_domain VARCHAR(32) NOT NULL COMMENT '业务域',
    trigger_count INT NOT NULL DEFAULT 0 COMMENT '触发次数',
    affected_order_count INT NOT NULL DEFAULT 0 COMMENT '影响订单数',
    affected_amount DECIMAL(12,2) DEFAULT NULL COMMENT '影响金额',
    latest_trigger_time DATETIME DEFAULT NULL COMMENT '最近触发时间',
    root_reason_summary VARCHAR(500) DEFAULT NULL COMMENT '根因摘要',
    current_status VARCHAR(16) NOT NULL DEFAULT 'OPEN' COMMENT '当前状态',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    delete_flag INT DEFAULT 0,
    UNIQUE KEY uk_ip_tenant_pain_code (tenant_id, pain_code),
    KEY idx_ip_tenant_id (tenant_id),
    KEY idx_ip_pain_level (pain_level),
    KEY idx_ip_domain (business_domain)
) COMMENT='租户高频经营痛点沉淀';
