SET @dbname = DATABASE();
SET @tablename = 't_login_log';

SET @col = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = @dbname AND TABLE_NAME = @tablename AND COLUMN_NAME = 'log_type');
SET @s = IF(@col=0, 'ALTER TABLE t_login_log ADD COLUMN log_type VARCHAR(20) DEFAULT ''LOGIN'' AFTER error_message', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @col = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = @dbname AND TABLE_NAME = @tablename AND COLUMN_NAME = 'biz_type');
SET @s = IF(@col=0, 'ALTER TABLE t_login_log ADD COLUMN biz_type VARCHAR(50) DEFAULT NULL AFTER log_type', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @col = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = @dbname AND TABLE_NAME = @tablename AND COLUMN_NAME = 'biz_id');
SET @s = IF(@col=0, 'ALTER TABLE t_login_log ADD COLUMN biz_id VARCHAR(64) DEFAULT NULL AFTER biz_type', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @col = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = @dbname AND TABLE_NAME = @tablename AND COLUMN_NAME = 'action');
SET @s = IF(@col=0, 'ALTER TABLE t_login_log ADD COLUMN action VARCHAR(50) DEFAULT NULL AFTER biz_id', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @col = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = @dbname AND TABLE_NAME = @tablename AND COLUMN_NAME = 'remark');
SET @s = IF(@col=0, 'ALTER TABLE t_login_log ADD COLUMN remark VARCHAR(500) DEFAULT NULL AFTER action', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @col = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = @dbname AND TABLE_NAME = @tablename AND COLUMN_NAME = 'tenant_id');
SET @s = IF(@col=0, 'ALTER TABLE t_login_log ADD COLUMN tenant_id BIGINT DEFAULT NULL AFTER remark', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @col = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = @dbname AND TABLE_NAME = @tablename AND INDEX_NAME = 'idx_login_log_tenant_id');
SET @s = IF(@col=0, 'ALTER TABLE t_login_log ADD INDEX idx_login_log_tenant_id (tenant_id)', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
