CREATE TABLE IF NOT EXISTS t_ec_sync_log (
    id                  BIGINT AUTO_INCREMENT PRIMARY KEY,
    tenant_id           BIGINT       NOT NULL,
    sync_type           VARCHAR(32)  NOT NULL,
    platform_code       VARCHAR(32)  NOT NULL,
    direction           VARCHAR(16)  NOT NULL DEFAULT 'OUTBOUND',
    style_id            BIGINT       NULL,
    sku_id              BIGINT       NULL,
    mapping_id          BIGINT       NULL,
    request_payload     TEXT         NULL,
    response_payload    TEXT         NULL,
    status              VARCHAR(16)  NOT NULL DEFAULT 'PENDING',
    retry_count         INT          NOT NULL DEFAULT 0,
    max_retries         INT          NOT NULL DEFAULT 3,
    next_retry_at       DATETIME     NULL,
    error_code          VARCHAR(64)  NULL,
    error_message       VARCHAR(1024) NULL,
    duration_ms         INT          NULL,
    triggered_by        VARCHAR(32)  NOT NULL DEFAULT 'AUTO',
    create_time         DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time         DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_tenant_status (tenant_id, status),
    INDEX idx_platform_type (platform_code, sync_type),
    INDEX idx_next_retry (status, next_retry_at),
    INDEX idx_create_time (create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
