CREATE TABLE IF NOT EXISTS t_warehouse_location (
    id VARCHAR(36) PRIMARY KEY,
    location_code VARCHAR(64) NOT NULL COMMENT '库位编码',
    location_name VARCHAR(128) COMMENT '库位名称',
    zone_code VARCHAR(32) COMMENT '库区编码',
    zone_name VARCHAR(64) COMMENT '库区名称',
    aisle_code VARCHAR(32) COMMENT '通道编码',
    rack_code VARCHAR(32) COMMENT '货架编码',
    level_code VARCHAR(16) COMMENT '层编码',
    position_code VARCHAR(16) COMMENT '位编码',
    location_type VARCHAR(32) COMMENT '库位类型: STORAGE/PICKING/STAGING/RETURN',
    warehouse_type VARCHAR(32) COMMENT '仓库类型: MATERIAL/FINISHED/SAMPLE',
    capacity INT DEFAULT 0 COMMENT '容量上限',
    used_capacity INT DEFAULT 0 COMMENT '已用容量',
    status VARCHAR(16) DEFAULT 'ACTIVE' COMMENT '状态: ACTIVE/DISABLED',
    description VARCHAR(256) COMMENT '描述',
    tenant_id BIGINT NOT NULL COMMENT '租户ID',
    create_by VARCHAR(36) COMMENT '创建人',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by VARCHAR(36) COMMENT '更新人',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    delete_flag INT DEFAULT 0 COMMENT '删除标记',
    UNIQUE KEY uk_location_code_tenant (location_code, tenant_id),
    KEY idx_tenant_id (tenant_id),
    KEY idx_warehouse_type (warehouse_type),
    KEY idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='库位管理';

CREATE TABLE IF NOT EXISTS t_stock_change_log (
    id VARCHAR(36) PRIMARY KEY,
    change_no VARCHAR(64) COMMENT '变更单号',
    change_type VARCHAR(32) NOT NULL COMMENT '变更类型: INBOUND/OUTBOUND/TRANSFER/CHECK/ADJUST',
    stock_type VARCHAR(32) NOT NULL COMMENT '库存类型: MATERIAL/FINISHED/SAMPLE',
    stock_id VARCHAR(36) COMMENT '库存记录ID',
    material_code VARCHAR(64) COMMENT '物料编码',
    style_no VARCHAR(64) COMMENT '款号',
    color VARCHAR(32) COMMENT '颜色',
    size VARCHAR(16) COMMENT '尺码',
    location_code VARCHAR(64) COMMENT '库位编码',
    before_quantity DECIMAL(15,2) COMMENT '变更前数量',
    change_quantity DECIMAL(15,2) COMMENT '变更数量',
    after_quantity DECIMAL(15,2) COMMENT '变更后数量',
    unit VARCHAR(16) COMMENT '单位',
    biz_type VARCHAR(32) COMMENT '业务类型: PURCHASE/PICKING/OUTSTOCK/CHECK/TRANSFER',
    biz_id VARCHAR(36) COMMENT '业务单据ID',
    biz_no VARCHAR(64) COMMENT '业务单号',
    operator_id VARCHAR(36) COMMENT '操作人ID',
    operator_name VARCHAR(64) COMMENT '操作人姓名',
    remark VARCHAR(256) COMMENT '备注',
    tenant_id BIGINT NOT NULL COMMENT '租户ID',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    KEY idx_tenant_id (tenant_id),
    KEY idx_change_type (change_type),
    KEY idx_stock_type (stock_type),
    KEY idx_biz_type (biz_type),
    KEY idx_create_time (create_time),
    KEY idx_material_code (material_code),
    KEY idx_style_no (style_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='库存变更流水';

CREATE TABLE IF NOT EXISTS t_stock_transfer (
    id VARCHAR(36) PRIMARY KEY,
    transfer_no VARCHAR(64) NOT NULL COMMENT '调拨单号',
    transfer_type VARCHAR(32) NOT NULL COMMENT '调拨类型: MATERIAL/FINISHED/SAMPLE',
    stock_type VARCHAR(32) COMMENT '库存类型',
    material_code VARCHAR(64) COMMENT '物料编码',
    style_no VARCHAR(64) COMMENT '款号',
    color VARCHAR(32) COMMENT '颜色',
    size VARCHAR(16) COMMENT '尺码',
    quantity INT NOT NULL COMMENT '调拨数量',
    from_location_code VARCHAR(64) NOT NULL COMMENT '调出库位编码',
    from_location_name VARCHAR(128) COMMENT '调出库位名称',
    to_location_code VARCHAR(64) NOT NULL COMMENT '调入库位编码',
    to_location_name VARCHAR(128) COMMENT '调入库位名称',
    status VARCHAR(16) DEFAULT 'PENDING' COMMENT '状态: PENDING/APPROVED/COMPLETED/CANCELLED',
    applicant_id VARCHAR(36) COMMENT '申请人ID',
    applicant_name VARCHAR(64) COMMENT '申请人姓名',
    approver_id VARCHAR(36) COMMENT '审批人ID',
    approver_name VARCHAR(64) COMMENT '审批人姓名',
    approve_time DATETIME COMMENT '审批时间',
    remark VARCHAR(256) COMMENT '备注',
    tenant_id BIGINT NOT NULL COMMENT '租户ID',
    create_by VARCHAR(36) COMMENT '创建人',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by VARCHAR(36) COMMENT '更新人',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    delete_flag INT DEFAULT 0 COMMENT '删除标记',
    KEY idx_tenant_id (tenant_id),
    KEY idx_transfer_no (transfer_no),
    KEY idx_status (status),
    KEY idx_create_time (create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='库存调拨';
