SET @c = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_agent_checkpoint' AND COLUMN_NAME='thread_id');
SET @s = IF(@c=0, 'ALTER TABLE t_agent_checkpoint ADD COLUMN thread_id VARCHAR(128) DEFAULT NULL', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
UPDATE t_agent_checkpoint SET thread_id = '' WHERE thread_id IS NULL;

SET @c = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_agent_checkpoint' AND COLUMN_NAME='node_id');
SET @s = IF(@c=0, 'ALTER TABLE t_agent_checkpoint ADD COLUMN node_id VARCHAR(128) DEFAULT NULL', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
UPDATE t_agent_checkpoint SET node_id = '' WHERE node_id IS NULL;

SET @c = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_agent_checkpoint' AND COLUMN_NAME='node_name');
SET @s = IF(@c=0, 'ALTER TABLE t_agent_checkpoint ADD COLUMN node_name VARCHAR(256) DEFAULT NULL', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @c = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_agent_checkpoint' AND COLUMN_NAME='state_json');
SET @s = IF(@c=0, 'ALTER TABLE t_agent_checkpoint ADD COLUMN state_json MEDIUMTEXT DEFAULT NULL', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @c = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_agent_checkpoint' AND COLUMN_NAME='metadata_json');
SET @s = IF(@c=0, 'ALTER TABLE t_agent_checkpoint ADD COLUMN metadata_json TEXT DEFAULT NULL', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @c = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_agent_checkpoint' AND COLUMN_NAME='step_index');
SET @s = IF(@c=0, 'ALTER TABLE t_agent_checkpoint ADD COLUMN step_index INT NOT NULL DEFAULT 0', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @c = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_agent_checkpoint' AND COLUMN_NAME='status');
SET @s = IF(@c=0, 'ALTER TABLE t_agent_checkpoint ADD COLUMN status VARCHAR(32) DEFAULT NULL', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
UPDATE t_agent_checkpoint SET status = 'ACTIVE' WHERE status IS NULL;

SET @c = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_agent_checkpoint' AND COLUMN_NAME='created_at');
SET @s = IF(@c=0, 'ALTER TABLE t_agent_checkpoint ADD COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP', 'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @idx = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_agent_checkpoint' AND INDEX_NAME='idx_acp_tenant_thread');
SET @s_idx = IF(@idx=0, 'ALTER TABLE t_agent_checkpoint ADD INDEX idx_acp_tenant_thread (tenant_id, thread_id)', 'SELECT 1');
PREPARE stmt FROM @s_idx; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @idx2 = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_agent_checkpoint' AND INDEX_NAME='idx_acp_thread_step');
SET @s_idx2 = IF(@idx2=0, 'ALTER TABLE t_agent_checkpoint ADD INDEX idx_acp_thread_step (thread_id, step_index)', 'SELECT 1');
PREPARE stmt FROM @s_idx2; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @idx3 = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='t_agent_checkpoint' AND INDEX_NAME='idx_acp_status');
SET @s_idx3 = IF(@idx3=0, 'ALTER TABLE t_agent_checkpoint ADD INDEX idx_acp_status (status)', 'SELECT 1');
PREPARE stmt FROM @s_idx3; EXECUTE stmt; DEALLOCATE PREPARE stmt;