-- 账单汇总表：统一收付款账单聚合
-- 所有模块（面料对账/成品对账/工资结算/费用报销/出货对账）审批通过后推送到此表
-- 替代原有 WagePaymentOrchestrator.listPendingPayables() 的查询时聚合模式

CREATE TABLE IF NOT EXISTS `t_bill_aggregation` (
    `id` VARCHAR(64) NOT NULL,
    `bill_no` VARCHAR(64) NOT NULL,
    `bill_type` VARCHAR(32) NOT NULL COMMENT 'PAYABLE=应付, RECEIVABLE=应收',
    `bill_category` VARCHAR(32) NOT NULL COMMENT 'MATERIAL=面料, PRODUCT=成品, EXTERNAL_FACTORY=外发厂, PAYROLL=工资, EXPENSE=费用报销, SHIPMENT=出货, DEDUCTION=扣款',
    `source_type` VARCHAR(64) DEFAULT NULL COMMENT '来源类型: MATERIAL_RECONCILIATION / SHIPMENT_RECONCILIATION / PAYROLL_SETTLEMENT / EXPENSE_REIMBURSEMENT',
    `source_id` VARCHAR(64) DEFAULT NULL,
    `source_no` VARCHAR(64) DEFAULT NULL,
    `counterparty_type` VARCHAR(32) DEFAULT NULL COMMENT 'SUPPLIER=供应商, CUSTOMER=客户, WORKER=员工, FACTORY=工厂',
    `counterparty_id` VARCHAR(64) DEFAULT NULL,
    `counterparty_name` VARCHAR(128) DEFAULT NULL,
    `order_id` VARCHAR(64) DEFAULT NULL,
    `order_no` VARCHAR(64) DEFAULT NULL,
    `style_no` VARCHAR(64) DEFAULT NULL,
    `amount` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    `settled_amount` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    `status` VARCHAR(32) NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING=待确认, CONFIRMED=已确认, SETTLING=结算中, SETTLED=已结清, CANCELLED=已取消',
    `settlement_month` VARCHAR(7) DEFAULT NULL COMMENT '结算月份 yyyy-MM',
    `remark` VARCHAR(512) DEFAULT NULL,
    `confirmed_by_id` VARCHAR(64) DEFAULT NULL,
    `confirmed_by_name` VARCHAR(64) DEFAULT NULL,
    `confirmed_at` DATETIME DEFAULT NULL,
    `settled_by_id` VARCHAR(64) DEFAULT NULL,
    `settled_by_name` VARCHAR(64) DEFAULT NULL,
    `settled_at` DATETIME DEFAULT NULL,
    `creator_id` VARCHAR(64) DEFAULT NULL,
    `creator_name` VARCHAR(64) DEFAULT NULL,
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `tenant_id` BIGINT NOT NULL,
    `delete_flag` INT NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_bill_no` (`bill_no`),
    UNIQUE KEY `uk_source` (`source_type`, `source_id`, `tenant_id`),
    KEY `idx_status` (`status`),
    KEY `idx_bill_type` (`bill_type`),
    KEY `idx_settlement_month` (`settlement_month`),
    KEY `idx_tenant_id` (`tenant_id`),
    KEY `idx_counterparty` (`counterparty_type`, `counterparty_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
