INSERT IGNORE INTO t_dict (dict_code, dict_label, dict_value, dict_type, sort, status) VALUES
('EASY', '易', 'EASY', 'process_difficulty', 1, 'ENABLED'),
('MEDIUM', '中', 'MEDIUM', 'process_difficulty', 2, 'ENABLED'),
('HARD', '难', 'HARD', 'process_difficulty', 3, 'ENABLED'),

('NORMAL', '普通', 'NORMAL', 'urgency_level', 1, 'ENABLED'),
('URGENT', '急单', 'URGENT', 'urgency_level', 2, 'ENABLED'),

('FIRST', '首单', 'FIRST', 'order_type', 1, 'ENABLED'),
('REORDER', '翻单', 'REORDER', 'order_type', 2, 'ENABLED'),

('FOB', 'FOB', 'FOB', 'order_biz_type', 1, 'ENABLED'),
('ODM', 'ODM', 'ODM', 'order_biz_type', 2, 'ENABLED'),
('OEM', 'OEM', 'OEM', 'order_biz_type', 3, 'ENABLED'),
('CMT', 'CMT', 'CMT', 'order_biz_type', 4, 'ENABLED'),

('SALES', '销售出库', 'SALES', 'outbound_type', 1, 'ENABLED'),
('TRANSFER', '调拨出库', 'TRANSFER', 'outbound_type', 2, 'ENABLED'),
('SCRAP', '报废出库', 'SCRAP', 'outbound_type', 3, 'ENABLED'),

('FABRIC', '面料', 'FABRIC', 'material_category', 1, 'ENABLED'),
('LINING', '里料', 'LINING', 'material_category', 2, 'ENABLED'),
('ACCESSORY', '辅料', 'ACCESSORY', 'material_category', 3, 'ENABLED'),

('INTERNAL', '内部工厂', 'INTERNAL', 'factory_label', 1, 'ENABLED'),
('EXTERNAL', '外部工厂', 'EXTERNAL', 'factory_label', 2, 'ENABLED'),

('PURCHASE', '采购', 'PURCHASE', 'progress_stage', 1, 'ENABLED'),
('CUTTING', '裁剪', 'CUTTING', 'progress_stage', 2, 'ENABLED'),
('SECONDARY', '二次工艺', 'SECONDARY', 'progress_stage', 3, 'ENABLED'),
('SEWING', '车缝', 'SEWING', 'progress_stage', 4, 'ENABLED'),
('FINISHING', '尾部', 'FINISHING', 'progress_stage', 5, 'ENABLED'),
('WAREHOUSING', '入库', 'WAREHOUSING', 'progress_stage', 6, 'ENABLED'),

('PASS', '通过', 'PASS', 'review_status', 1, 'ENABLED'),
('REWORK', '需修改', 'REWORK', 'review_status', 2, 'ENABLED'),
('REJECT', '不通过', 'REJECT', 'review_status', 3, 'ENABLED'),

('PENDING', '待处理', 'PENDING', 'secondary_process_status', 1, 'ENABLED'),
('PROCESSING', '处理中', 'PROCESSING', 'secondary_process_status', 2, 'ENABLED'),
('COMPLETED', '已完成', 'COMPLETED', 'secondary_process_status', 3, 'ENABLED'),
('CANCELLED', '已取消', 'CANCELLED', 'secondary_process_status', 4, 'ENABLED'),

('WOMAN', '女装', 'WOMAN', 'category', 1, 'ENABLED'),
('MAN', '男装', 'MAN', 'category', 2, 'ENABLED'),
('KIDS', '童装', 'KIDS', 'category', 3, 'ENABLED'),
('WCMAN', '女童装', 'WCMAN', 'category', 4, 'ENABLED'),
('UNISEX', '男女同款', 'UNISEX', 'category', 5, 'ENABLED'),
('SPORT', '运动装', 'SPORT', 'category', 6, 'ENABLED'),
('UNDERWEAR', '内衣', 'UNDERWEAR', 'category', 7, 'ENABLED'),
('T_SHIRT', 'T恤', 'T_SHIRT', 'category', 8, 'ENABLED'),
('SHIRT', '衬衫', 'SHIRT', 'category', 9, 'ENABLED'),
('PANTS', '裤子', 'PANTS', 'category', 10, 'ENABLED'),
('SKIRT', '裙子', 'SKIRT', 'category', 11, 'ENABLED'),
('JACKET', '外套', 'JACKET', 'category', 12, 'ENABLED'),
('COAT', '大衣', 'COAT', 'category', 13, 'ENABLED'),
('DRESS', '连衣裙', 'DRESS', 'category', 14, 'ENABLED'),
('SWEATER', '毛衣', 'SWEATER', 'category', 15, 'ENABLED'),
('HOODIE', '卫衣', 'HOODIE', 'category', 16, 'ENABLED'),
('JEANS', '牛仔裤', 'JEANS', 'category', 17, 'ENABLED'),
('SHORTS', '短裤', 'SHORTS', 'category', 18, 'ENABLED'),
('POLO', 'POLO衫', 'POLO', 'category', 19, 'ENABLED'),
('WINDBREAKER', '风衣', 'WINDBREAKER', 'category', 20, 'ENABLED'),
('DOWN', '羽绒服', 'DOWN', 'category', 21, 'ENABLED'),
('VEST', '马甲', 'VEST', 'category', 22, 'ENABLED'),
('SUIT', '套装', 'SUIT', 'category', 23, 'ENABLED'),
('YOGA', '瑜伽服', 'YOGA', 'category', 24, 'ENABLED'),
('SUN_PROTECT', '防晒服', 'SUN_PROTECT', 'category', 25, 'ENABLED'),
('CASUAL', '休闲装', 'CASUAL', 'category', 26, 'ENABLED'),
('FASHION', '时装', 'FASHION', 'category', 27, 'ENABLED'),
('WORKWEAR', '工装', 'WORKWEAR', 'category', 28, 'ENABLED'),
('MATERIAL', '面辅料供应商', 'MATERIAL', 'factory_type', 1, 'ENABLED'),
('OUTSOURCE', '外发供应商', 'OUTSOURCE', 'factory_type', 2, 'ENABLED'),

('SPRING', '春季', 'SPRING', 'season', 1, 'ENABLED'),
('SUMMER', '夏季', 'SUMMER', 'season', 2, 'ENABLED'),
('AUTUMN', '秋季', 'AUTUMN', 'season', 3, 'ENABLED'),
('WINTER', '冬季', 'WINTER', 'season', 4, 'ENABLED'),
('SPRING_SUMMER', '春夏', 'SPRING_SUMMER', 'season', 5, 'ENABLED'),
('AUTUMN_WINTER', '秋冬', 'AUTUMN_WINTER', 'season', 6, 'ENABLED'),

('PROCESS', '工序进度单价', 'PROCESS', 'template_type', 1, 'ENABLED'),
('PROCESS_SIZE', '多码工序进度单价', 'PROCESS_SIZE', 'template_type', 2, 'ENABLED'),

('NORMAL_STATUS', '正式', 'NORMAL_STATUS', 'employment_status', 1, 'ENABLED'),
('PROBATION', '试用期', 'PROBATION', 'employment_status', 2, 'ENABLED'),
('TEMPORARY', '临时工', 'TEMPORARY', 'employment_status', 3, 'ENABLED');
