CREATE TABLE IF NOT EXISTS t_order_decision_snapshot (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    order_id VARCHAR(64),
    order_no VARCHAR(64),
    style_id VARCHAR(64),
    style_no VARCHAR(64),
    style_name VARCHAR(128),
    style_category VARCHAR(64),
    factory_mode VARCHAR(32),
    factory_id BIGINT,
    factory_name VARCHAR(128),
    selected_pricing_mode VARCHAR(32),
    selected_order_unit_price DECIMAL(12,4),
    selected_scatter_pricing_mode VARCHAR(32),
    selected_scatter_unit_price DECIMAL(12,4),
    process_unit_price DECIMAL(12,4),
    size_unit_price DECIMAL(12,4),
    total_cost_unit_price DECIMAL(12,4),
    quotation_unit_price DECIMAL(12,4),
    ai_recommended_pricing_mode VARCHAR(32),
    ai_recommended_factory_mode VARCHAR(32),
    ai_recommended_unit_price DECIMAL(12,4),
    order_quantity INT,
    color_count INT,
    size_count INT,
    scatter_extra_per_piece DECIMAL(12,4),
    recommendation_reason TEXT,
    pricing_context_json JSON,
    decision_type VARCHAR(32),
    decision_data JSON,
    ai_suggestion TEXT,
    ai_confidence DECIMAL(5,2),
    user_choice VARCHAR(32),
    user_modified_fields JSON,
    created_by VARCHAR(64),
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_ods_tenant_order (tenant_id, order_no),
    INDEX idx_ods_tenant_style (tenant_id, style_no),
    INDEX idx_ods_tenant_created (tenant_id, create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
