-- 快递单表
CREATE TABLE IF NOT EXISTS t_express_order (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    tracking_no VARCHAR(100) NOT NULL COMMENT '快递单号',
    company_code VARCHAR(50) COMMENT '快递公司编码',
    company_name VARCHAR(100) COMMENT '快递公司名称',
    order_no VARCHAR(100) COMMENT '关联订单号',
    shipment_type TINYINT DEFAULT 1 COMMENT '发货类型: 1-成品发货, 2-样衣发货, 3-物料发货',
    receiver_name VARCHAR(100) COMMENT '收件人姓名',
    receiver_phone VARCHAR(50) COMMENT '收件人电话',
    receiver_address TEXT COMMENT '收件人地址',
    sender_name VARCHAR(100) COMMENT '寄件人姓名',
    sender_phone VARCHAR(50) COMMENT '寄件人电话',
    sender_address TEXT COMMENT '寄件人地址',
    goods_name VARCHAR(200) COMMENT '货物名称',
    goods_quantity INT DEFAULT 1 COMMENT '货物数量',
    weight DECIMAL(10,2) COMMENT '重量(kg)',
    freight DECIMAL(10,2) COMMENT '运费',
    status TINYINT DEFAULT 0 COMMENT '状态: 0-待发货, 1-已发货, 2-运输中, 3-已到达, 4-已签收, 5-异常, 6-已退回',
    ship_time DATETIME COMMENT '发货时间',
    sign_time DATETIME COMMENT '签收时间',
    sign_person VARCHAR(100) COMMENT '签收人',
    remark TEXT COMMENT '备注',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    create_by VARCHAR(50) COMMENT '创建人',
    update_by VARCHAR(50) COMMENT '更新人',
    INDEX idx_tracking_no (tracking_no),
    INDEX idx_order_no (order_no),
    INDEX idx_status (status),
    INDEX idx_company_code (company_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='快递单表';

-- 电商订单表
CREATE TABLE IF NOT EXISTS t_ecommerce_order (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    order_no VARCHAR(100) NOT NULL COMMENT '订单编号',
    platform VARCHAR(20) COMMENT '电商平台: TB-淘宝, JD-京东, PDD-拼多多, DY-抖音',
    platform_order_no VARCHAR(100) COMMENT '平台订单号',
    shop_name VARCHAR(200) COMMENT '店铺名称',
    buyer_nick VARCHAR(100) COMMENT '买家昵称',
    status TINYINT DEFAULT 0 COMMENT '状态: 0-待付款, 1-待发货, 2-已发货, 3-已完成, 4-已取消, 5-退款中',
    total_amount DECIMAL(12,2) COMMENT '订单金额',
    pay_amount DECIMAL(12,2) COMMENT '实付金额',
    freight DECIMAL(10,2) COMMENT '运费',
    discount DECIMAL(10,2) COMMENT '优惠金额',
    pay_type VARCHAR(50) COMMENT '支付方式',
    pay_time DATETIME COMMENT '支付时间',
    ship_time DATETIME COMMENT '发货时间',
    complete_time DATETIME COMMENT '完成时间',
    receiver_name VARCHAR(100) COMMENT '收件人姓名',
    receiver_phone VARCHAR(50) COMMENT '收件人电话',
    receiver_address TEXT COMMENT '收件人地址',
    tracking_no VARCHAR(100) COMMENT '快递单号',
    express_company VARCHAR(100) COMMENT '快递公司',
    buyer_remark TEXT COMMENT '买家备注',
    seller_remark TEXT COMMENT '卖家备注',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_order_no (order_no),
    INDEX idx_platform (platform),
    INDEX idx_status (status),
    INDEX idx_shop_name (shop_name),
    INDEX idx_create_time (create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='电商订单表';
