CREATE TABLE IF NOT EXISTS `t_order_decision_snapshot` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint DEFAULT NULL,
  `order_id` varchar(64) NOT NULL,
  `order_no` varchar(64) DEFAULT NULL,
  `style_id` varchar(64) DEFAULT NULL,
  `style_no` varchar(64) DEFAULT NULL,
  `style_name` varchar(128) DEFAULT NULL,
  `style_category` varchar(64) DEFAULT NULL,
  `factory_mode` varchar(32) DEFAULT NULL,
  `factory_id` varchar(64) DEFAULT NULL,
  `factory_name` varchar(128) DEFAULT NULL,
  `selected_pricing_mode` varchar(32) DEFAULT NULL,
  `selected_order_unit_price` decimal(12,2) DEFAULT NULL,
  `selected_scatter_pricing_mode` varchar(32) DEFAULT NULL,
  `selected_scatter_unit_price` decimal(12,2) DEFAULT NULL,
  `process_unit_price` decimal(12,2) DEFAULT NULL,
  `size_unit_price` decimal(12,2) DEFAULT NULL,
  `total_cost_unit_price` decimal(12,2) DEFAULT NULL,
  `quotation_unit_price` decimal(12,2) DEFAULT NULL,
  `ai_recommended_unit_price` decimal(12,2) DEFAULT NULL,
  `ai_recommended_pricing_mode` varchar(32) DEFAULT NULL,
  `ai_recommended_factory_mode` varchar(32) DEFAULT NULL,
  `order_quantity` int DEFAULT NULL,
  `color_count` int DEFAULT NULL,
  `size_count` int DEFAULT NULL,
  `scatter_extra_per_piece` decimal(12,2) DEFAULT NULL,
  `recommendation_reason` varchar(1000) DEFAULT NULL,
  `pricing_context_json` text,
  `created_by` varchar(64) DEFAULT NULL,
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_order_decision_snapshot_order` (`tenant_id`,`order_id`),
  KEY `idx_order_decision_snapshot_style` (`tenant_id`,`style_no`,`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `t_order_learning_outcome` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint DEFAULT NULL,
  `order_id` varchar(64) NOT NULL,
  `order_no` varchar(64) DEFAULT NULL,
  `decision_snapshot_id` bigint DEFAULT NULL,
  `actual_factory_id` varchar(64) DEFAULT NULL,
  `actual_factory_name` varchar(128) DEFAULT NULL,
  `planned_finish_date` datetime DEFAULT NULL,
  `actual_finish_date` datetime DEFAULT NULL,
  `delay_days` int DEFAULT 0,
  `estimated_unit_cost` decimal(12,2) DEFAULT NULL,
  `actual_unit_cost` decimal(12,2) DEFAULT NULL,
  `estimated_total_cost` decimal(14,2) DEFAULT NULL,
  `actual_total_cost` decimal(14,2) DEFAULT NULL,
  `actual_scatter_extra_cost` decimal(14,2) DEFAULT NULL,
  `cost_deviation_rate` decimal(10,4) DEFAULT NULL,
  `replenishment_count` int DEFAULT 0,
  `rework_count` int DEFAULT 0,
  `outcome_score` decimal(10,2) DEFAULT NULL,
  `outcome_summary` varchar(500) DEFAULT NULL,
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_order_learning_outcome_order` (`tenant_id`,`order_id`),
  KEY `idx_order_learning_outcome_snapshot` (`tenant_id`,`decision_snapshot_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
