filepath = 'miniprogram/pages/warehouse/sample/list/index.wxml'
with open(filepath, 'r', encoding='utf-8') as f:
    lines = f.readlines()

before = lines[:110]   # lines 1-110 unchanged
tail   = lines[-1:]    # last </view> of page container

operation_modal = (
  "  <!-- 操作弹窗（入库/借出/归还）—— mp-modal 通用组件 -->\n"
  "  <mp-modal\n"
  "    visible=\"{{operationModal.visible}}\"\n"
  "    title=\"{{operationModal.title}}\"\n"
  "    size=\"large\"\n"
  "    bind:close=\"closeOperationModal\"\n"
  "  >\n"
  "    <view class=\"modal-body\">\n"
  "      <!-- 款号输入（归还模式不显示） -->\n"
  "      <view class=\"form-item\" wx:if=\"{{operationModal.type !== 'return'}}\">\n"
  "        <text class=\"label\">款号</text>\n"
  "        <view class=\"input-wrap\">\n"
  "          <input value=\"{{operationModal.formData.styleNo}}\" placeholder=\"请输入款号\" bindinput=\"onOperationInput\" data-field=\"styleNo\" />\n"
  "          <view class=\"scan-btn\" bindtap=\"handleScanStyle\">\n"
  "            <image src=\"/assets/icons/scan.svg\" mode=\"aspectFit\" style=\"width: 36rpx; height: 36rpx;\" />\n"
  "          </view>\n"
  "        </view>\n"
  "      </view>\n"
  "\n"
  "      <!-- 入库专用字段 -->\n"
  "      <block wx:if=\"{{operationModal.type === 'inbound'}}\">\n"
  "        <view class=\"form-item\">\n"
  "          <text class=\"label\">款式名称</text>\n"
  "          <input value=\"{{operationModal.formData.styleName}}\" placeholder=\"选填\" bindinput=\"onOperationInput\" data-field=\"styleName\" />\n"
  "        </view>\n"
  "        <view class=\"form-item\">\n"
  "          <text class=\"label\">样衣类型</text>\n"
  "          <view class=\"inline-selector\">\n"
  "            <scroll-view class=\"inline-selector-list\" scroll-y=\"{{true}}\" enhanced=\"{{true}}\" show-scrollbar=\"{{false}}\">\n"
  "              <view\n"
  "                wx:for=\"{{operationModal.sampleTypes}}\"\n"
  "                wx:key=\"key\"\n"
  "                class=\"inline-selector-item {{operationModal.typeIndex == index ? 'active' : ''}}\"\n"
  "                data-index=\"{{index}}\"\n"
  "                bindtap=\"onTypeSelect\">\n"
  "                <view class=\"inline-selector-left\">\n"
  "                  <view class=\"inline-selector-radio {{operationModal.typeIndex == index ? 'checked' : ''}}\">\n"
  "                    <view wx:if=\"{{operationModal.typeIndex == index}}\" class=\"inline-selector-radio-dot\"></view>\n"
  "                  </view>\n"
  "                  <text class=\"inline-selector-label\">{{item.label}}</text>\n"
  "                </view>\n"
  "              </view>\n"
  "            </scroll-view>\n"
  "          </view>\n"
  "        </view>\n"
  "        <view class=\"form-row\">\n"
  "          <view class=\"form-item flex-1\">\n"
  "            <text class=\"label\">颜色</text>\n"
  "            <input value=\"{{operationModal.formData.color}}\" placeholder=\"如: 红色\" bindinput=\"onOperationInput\" data-field=\"color\" />\n"
  "          </view>\n"
  "          <view class=\"form-item flex-1 ml-20\">\n"
  "            <text class=\"label\">尺码</text>\n"
  "            <input value=\"{{operationModal.formData.size}}\" placeholder=\"如: M\" bindinput=\"onOperationInput\" data-field=\"size\" />\n"
  "          </view>\n"
  "        </view>\n"
  "        <view class=\"form-item\">\n"
  "          <text class=\"label\">存放位置</text>\n"
  "          <input value=\"{{operationModal.formData.location}}\" placeholder=\"选填\" bindinput=\"onOperationInput\" data-field=\"location\" />\n"
  "        </view>\n"
  "      </block>\n"
  "\n"
  "      <!-- 借出专用字段 -->\n"
  "      <block wx:if=\"{{operationModal.type === 'loan'}}\">\n"
  "        <view class=\"stock-selection\" wx:if=\"{{operationModal.stockList.length > 0}}\">\n"
  "          <text class=\"section-label\">请选择借出规格：</text>\n"
  "          <view\n"
  "            class=\"stock-item {{operationModal.selectedStockId === item.id ? 'active' : ''}}\"\n"
  "            wx:for=\"{{operationModal.stockList}}\"\n"
  "            wx:key=\"id\"\n"
  "            bindtap=\"onSelectStock\"\n"
  "            data-id=\"{{item.id}}\"\n"
  "          >\n"
  "            <view class=\"stock-info\">\n"
  "              <text class=\"stock-spec\">{{item.color}} / {{item.size}}</text>\n"
  "              <text class=\"stock-type\">{{item.sampleType}}</text>\n"
  "            </view>\n"
  "            <view class=\"stock-qty\">可用: {{item.quantity - item.loanedQuantity}}</view>\n"
  "          </view>\n"
  "        </view>\n"
  "        <view class=\"loading-stock\" wx:if=\"{{operationModal.stockLoading}}\">查询库存中...</view>\n"
  "        <view class=\"form-item\">\n"
  "          <text class=\"label\">借用人</text>\n"
  "          <input value=\"{{operationModal.formData.borrower}}\" placeholder=\"请输入姓名\" bindinput=\"onOperationInput\" data-field=\"borrower\" />\n"
  "        </view>\n"
  "        <view class=\"form-item\">\n"
  "          <text class=\"label\">预计归还时间</text>\n"
  "          <date-picker value=\"{{operationModal.returnDate}}\" placeholder=\"请选择日期\" bindchange=\"onDateChange\" />\n"
  "        </view>\n"
  "      </block>\n"
  "\n"
  "      <!-- 归还专用字段 -->\n"
  "      <block wx:if=\"{{operationModal.type === 'return'}}\">\n"
  "        <view class=\"form-item\">\n"
  "          <text class=\"label\">借出单号</text>\n"
  "          <view class=\"input-wrap\">\n"
  "            <input value=\"{{operationModal.formData.loanId}}\" placeholder=\"请输入借出记录ID\" bindinput=\"onOperationInput\" data-field=\"loanId\" />\n"
  "            <view class=\"scan-btn\" bindtap=\"handleScanLoan\">\n"
  "              <image src=\"/assets/icons/scan.svg\" mode=\"aspectFit\" style=\"width: 36rpx; height: 36rpx;\" />\n"
  "            </view>\n"
  "          </view>\n"
  "        </view>\n"
  "      </block>\n"
  "\n"
  "      <!-- 数量 -->\n"
  "      <view class=\"form-item\">\n"
  "        <text class=\"label\">数量</text>\n"
  "        <input type=\"number\" value=\"{{operationModal.formData.quantity}}\" bindinput=\"onOperationInput\" data-field=\"quantity\" />\n"
  "      </view>\n"
  "\n"
  "      <!-- 备注 -->\n"
  "      <view class=\"form-item\">\n"
  "        <text class=\"label\">备注</text>\n"
  "        <textarea value=\"{{operationModal.formData.remark}}\" placeholder=\"选填\" bindinput=\"onOperationInput\" data-field=\"remark\" style=\"height: 100rpx;\" />\n"
  "      </view>\n"
  "    </view>\n"
  "    <view class=\"modal-actions\">\n"
  "      <view class=\"btn cancel\" bindtap=\"closeOperationModal\">取消</view>\n"
  "      <view class=\"btn ok {{operationModal.submitting ? 'disabled' : ''}}\" bindtap=\"onSubmitOperation\">\n"
  "        {{operationModal.submitting ? '提交中...' : '确认'}}\n"
  "      </view>\n"
  "    </view>\n"
  "  </mp-modal>\n"
  "\n"
)

loan_modal = (
  "  <!-- 借出记录弹窗 —— mp-modal 通用组件 -->\n"
  "  <mp-modal\n"
  "    visible=\"{{loanModal.visible}}\"\n"
  "    title=\"借调记录 - {{loanModal.styleNo}}\"\n"
  "    bind:close=\"closeLoanModal\"\n"
  "  >\n"
  "    <view class=\"modal-body\">\n"
  "      <view wx:if=\"{{loanModal.loading}}\" class=\"loading-state\">加载中...</view>\n"
  "      <view wx:elif=\"{{loanModal.list.length > 0}}\" class=\"loan-list\">\n"
  "        <view class=\"loan-item\" wx:for=\"{{loanModal.list}}\" wx:key=\"id\">\n"
  "          <view class=\"loan-header\">\n"
  "            <text class=\"loan-borrower\">{{item.borrower}}</text>\n"
  "            <text class=\"loan-status {{item.status}}\">{{item.statusText}}</text>\n"
  "          </view>\n"
  "          <view class=\"loan-info\"><text class=\"loan-label\">数量:</text><text class=\"loan-value\">{{item.quantity}}</text></view>\n"
  "          <view class=\"loan-info\"><text class=\"loan-label\">借出时间:</text><text class=\"loan-value\">{{item.loanDate}}</text></view>\n"
  "          <view class=\"loan-info\" wx:if=\"{{item.expectedReturnDate}}\">\n"
  "            <text class=\"loan-label\">预计归还:</text><text class=\"loan-value\">{{item.expectedReturnDate}}</text>\n"
  "          </view>\n"
  "          <view class=\"loan-info\" wx:if=\"{{item.returnDate}}\">\n"
  "            <text class=\"loan-label\">归还时间:</text><text class=\"loan-value\">{{item.returnDate}}</text>\n"
  "          </view>\n"
  "        </view>\n"
  "      </view>\n"
  "      <view wx:else class=\"empty-state\">暂无借调记录</view>\n"
  "    </view>\n"
  "    <view class=\"modal-actions\">\n"
  "      <view class=\"btn cancel full-width\" bindtap=\"closeLoanModal\">关闭</view>\n"
  "    </view>\n"
  "  </mp-modal>\n"
)

new_lines = before + [operation_modal] + [loan_modal] + tail

with open(filepath, 'w', encoding='utf-8') as f:
    f.writelines(new_lines)

with open(filepath, 'r', encoding='utf-8') as f:
    result = f.read()
print('mp-modal count:', result.count('mp-modal'))
print('old modal remaining:', result.count('class="modal"'))
print('total lines:', result.count('\n'))
